{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.12.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.12.0+1.21.1.jar",
          "url": "filament-0.12.0+1.21.1.jar",
          "size": 1351353,
          "sha512": "5cf26727fc4646a60979c0cb6c00917f28dcfd7d6e52c21b738aab1cbcf3ea3ba55b2cf9f2479c2c3a3c2b2044fd75507899eb375edfbcdf276f932310827344",
          "sha256": "31441376452d527cc57e46ba85a05879bd110e073af35acc2494ed341f3f6a39",
          "sha1": "3832999d165ab9464c9d373cf721df53ee235c00",
          "md5": "c91d8aba3acb006de26d7eccb3de82ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.20+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.0+1.21.1.jar",
          "url": "filament-0.12.0+1.21.1.jar",
          "size": 1351353,
          "sha512": "5cf26727fc4646a60979c0cb6c00917f28dcfd7d6e52c21b738aab1cbcf3ea3ba55b2cf9f2479c2c3a3c2b2044fd75507899eb375edfbcdf276f932310827344",
          "sha256": "31441376452d527cc57e46ba85a05879bd110e073af35acc2494ed341f3f6a39",
          "sha1": "3832999d165ab9464c9d373cf721df53ee235c00",
          "md5": "c91d8aba3acb006de26d7eccb3de82ff"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.0+1.21.1-all.jar",
          "url": "filament-0.12.0+1.21.1-all.jar",
          "size": 792447,
          "sha512": "4f101bfcc9387aed65946fe496af178452d4d6047b8fed6137d63ace2c665179aa7d2bca56a9e78368db0457aef4b153e6258cd56fad9bfc2eb6491fa6e7c157",
          "sha256": "211deb616956cc438d2a275695d023c74dbe58f69a3b07228bb168d21a665ad3",
          "sha1": "35d062fbb56aa66d568170106f8e283cdd2d21f9",
          "md5": "7cbb42941272768efae97f63a1e9b431"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.12.0+1.21.1-sources.jar",
          "url": "filament-0.12.0+1.21.1-sources.jar",
          "size": 187326,
          "sha512": "fd699b50fc7c855787a8b9f43d9f35a7877ad05a66a0561effe062ca8802c8498128ff3ba7b00bed455229be01bcdb9d858880fee56fe7bcc4c1f20a1226766e",
          "sha256": "7c240d05ec61196814d7af57ffaa677eed2dbfd4d43b925bd9c9d9568e5e9323",
          "sha1": "eaac3b4610bd57f6ac5efad6e640a09f355cab59",
          "md5": "1e34194340711ff2db091dfb699b88af"
        }
      ]
    }
  ]
}
