{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.9.13+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.9.13+1.21.1.jar",
          "url": "filament-0.9.13+1.21.1.jar",
          "size": 949921,
          "sha512": "f3bef6cf485a90b85834e522d8de0926d8d85e740354cb72a578aeb51abc659fb9cfe324605f3f4c03227f71e84110a2c0e11e4949b02d90afea1d7ff5532f2a",
          "sha256": "f73314b37f9e16ded2f23231b06897ff6464cad910b6a361d31cd8a3f76d947d",
          "sha1": "1efa36e9db49d9945bdc8f8f2efe1c5a59c45897",
          "md5": "f28c2ef56eb6ca1cac7876d89012e1bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.13+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.9.13+1.21.1.jar",
          "url": "filament-0.9.13+1.21.1.jar",
          "size": 949921,
          "sha512": "f3bef6cf485a90b85834e522d8de0926d8d85e740354cb72a578aeb51abc659fb9cfe324605f3f4c03227f71e84110a2c0e11e4949b02d90afea1d7ff5532f2a",
          "sha256": "f73314b37f9e16ded2f23231b06897ff6464cad910b6a361d31cd8a3f76d947d",
          "sha1": "1efa36e9db49d9945bdc8f8f2efe1c5a59c45897",
          "md5": "f28c2ef56eb6ca1cac7876d89012e1bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.9.13+1.21.1-sources.jar",
          "url": "filament-0.9.13+1.21.1-sources.jar",
          "size": 165323,
          "sha512": "69bda7ccd8bf8e4d83e3fda138d526936d76d08a1fe941d6e6b807df8049cbe6ee4a0fa5085973ad722911642691cbd3e1ddd05ec6e70f35a81843aee7e1f89e",
          "sha256": "06bbe0e673feb1be1c9277d65941fd622690fa9a1bbae2361de11e6f0fbaf7ee",
          "sha1": "a9f1b953365a2e591cdce47a3e569ea25eda47b4",
          "md5": "3572fcb98d99b77489544b89aa89fa8d"
        }
      ]
    }
  ]
}
