{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.7.2+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.7.2+1.21.jar",
          "url": "filament-0.7.2+1.21.jar",
          "size": 630186,
          "sha512": "c3ff58d98b4f2b4713789a8b8fac2c9c1c1ed246002a08c68ce0c74330cec31fbd062f3722673811f43358c92be34e3daec40c0c6d960c3c0cd5d72ea9b3892a",
          "sha256": "9b5d8338ffabf11cd77949e9a5e5ed0c231313856b488398d88811edc07c7d10",
          "sha1": "6eb93f6aa8db563b156d913df29d7f57687c7027",
          "md5": "f77bf0a5004facf5a583352a80b3dab6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.7.2+1.21.jar",
          "url": "filament-0.7.2+1.21.jar",
          "size": 630186,
          "sha512": "c3ff58d98b4f2b4713789a8b8fac2c9c1c1ed246002a08c68ce0c74330cec31fbd062f3722673811f43358c92be34e3daec40c0c6d960c3c0cd5d72ea9b3892a",
          "sha256": "9b5d8338ffabf11cd77949e9a5e5ed0c231313856b488398d88811edc07c7d10",
          "sha1": "6eb93f6aa8db563b156d913df29d7f57687c7027",
          "md5": "f77bf0a5004facf5a583352a80b3dab6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.7.2+1.21-sources.jar",
          "url": "filament-0.7.2+1.21-sources.jar",
          "size": 117435,
          "sha512": "1d4b7daf450ac7b1b55c469d3eb3b951d8b375059e0c17dbdfbfd618a08c8007b97858f8fa9ff911d8f948ea497a9893005797f51de96bd73de11e9d6bc7ebd2",
          "sha256": "3670647c01cccd80f04413fd61a1ca0024cb1de9d8b5a46ff49e93f761f59784",
          "sha1": "bb965d23a1f06396d20dddea2d0d0bdfad6b02ed",
          "md5": "280811815a1af09fdfda6a5411649404"
        }
      ]
    }
  ]
}
