{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "1.8.5+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-1.8.5+1.21.11.jar",
          "url": "blockbench-import-library-1.8.5+1.21.11.jar",
          "size": 356006,
          "sha512": "1ef2483d69e3eab9922e3a9b51d46e465db6d38bb98e277857220eb02ca9fbcd0b0b7b0eb032a071d9d812ae2c911e08665bc1e97d30fd42e80e96d9c5d44eb6",
          "sha256": "0baed87e6690dc060b2045ff1e99ac25ac18008cc07ce38b9d59fc8863fee41d",
          "sha1": "27757773e78131523f72321027c546bf80b307cc",
          "md5": "220fc8e2e63a522aa6cab04547dabb42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-1.8.5+1.21.11.jar",
          "url": "blockbench-import-library-1.8.5+1.21.11.jar",
          "size": 356006,
          "sha512": "1ef2483d69e3eab9922e3a9b51d46e465db6d38bb98e277857220eb02ca9fbcd0b0b7b0eb032a071d9d812ae2c911e08665bc1e97d30fd42e80e96d9c5d44eb6",
          "sha256": "0baed87e6690dc060b2045ff1e99ac25ac18008cc07ce38b9d59fc8863fee41d",
          "sha1": "27757773e78131523f72321027c546bf80b307cc",
          "md5": "220fc8e2e63a522aa6cab04547dabb42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-1.8.5+1.21.11-sources.jar",
          "url": "blockbench-import-library-1.8.5+1.21.11-sources.jar",
          "size": 122840,
          "sha512": "17c6df4b2b1c32e697b0ea938aa8242d78e56b004b83859c569db7e17ffc081a91e82c9246b3096332f71e315b71143d3de7da87bf68ad47729e5ad2465023aa",
          "sha256": "24d9ddcc3364a35f9ce5f2ee740c4bbaf4bf380c8dcdf433c8ccb2c8113b10b9",
          "sha1": "5cd5cd9e110f2a7c69ad26f92e3175c233fa7c7c",
          "md5": "0d4dfd35f5c8172749349c2e4d94f524"
        }
      ]
    }
  ]
}
