{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.12.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.12.1+1.21.1.jar",
          "url": "filament-0.12.1+1.21.1.jar",
          "size": 1351459,
          "sha512": "878245a7a45bb56d35b53d93a1ff2231415aea53192b4e47eed4712e7246c9f584d14e2d28375470509622ac2cbc2236cf0f0d7fdb6a73ed6e617d964f52bf36",
          "sha256": "5c465ab0ea72ec8ed7cc7f41bb6ae12babd3a43b6dd0f5ed7dccdd10bbb8f3dd",
          "sha1": "52621d6aa48f82f00f0efe47a36805328b6b0675",
          "md5": "5269417f72939aa2ed9fbef4657745d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.20+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.1+1.21.1.jar",
          "url": "filament-0.12.1+1.21.1.jar",
          "size": 1351459,
          "sha512": "878245a7a45bb56d35b53d93a1ff2231415aea53192b4e47eed4712e7246c9f584d14e2d28375470509622ac2cbc2236cf0f0d7fdb6a73ed6e617d964f52bf36",
          "sha256": "5c465ab0ea72ec8ed7cc7f41bb6ae12babd3a43b6dd0f5ed7dccdd10bbb8f3dd",
          "sha1": "52621d6aa48f82f00f0efe47a36805328b6b0675",
          "md5": "5269417f72939aa2ed9fbef4657745d8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.1+1.21.1-all.jar",
          "url": "filament-0.12.1+1.21.1-all.jar",
          "size": 792566,
          "sha512": "9bbf39343b4a5f8fdcb0fcd90a8af095e38f6a0620ce2cc14a9f970d5b9bca5bf76671a6bdaa0bc0685afa8f5448da8f2de3b34b7f10162bf125cef623517100",
          "sha256": "d7bbaa23cbb28cef08de20f9045413ff6cb96dfbd16522dd597f56e6d5d623da",
          "sha1": "6bdc22cdfc41d24826612a91b291f78af3149604",
          "md5": "b4e661f89e2693d2355f93f175d1abe4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.12.1+1.21.1-sources.jar",
          "url": "filament-0.12.1+1.21.1-sources.jar",
          "size": 187358,
          "sha512": "9098084d688f1ac09f77cb9ad0feaee4b6e0ffe779b051871ee0d6815181cf8a22bb182eb89f5c91289c0805b1e30706f2a42b6db1abd0809c63620cf7446e19",
          "sha256": "31b39756b6b1728fb3dbb2e406e7dc159d837cc2b5ccec3b47dee7e8448d3c66",
          "sha1": "aa3788b512648fb5e61b6095cfe606b6f8453d27",
          "md5": "b3715e30b69b2cae84803074660ad785"
        }
      ]
    }
  ]
}
