{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.8+1.21.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.8+1.21.9.jar",
          "url": "filament-1.3.8+1.21.9.jar",
          "size": 3051753,
          "sha512": "b289ff8e255217cf7a8344493e8ee0d59851121ea70b494764eabebd6ebd8ba77c40273677049c50b4af6bcacfaa7dfa0b10edef9045431b8a2cf44105b90c08",
          "sha256": "dea84fe5dbf8afe4605e36545992d0ad9179cdfc8933ddffe8256d23d477434f",
          "sha1": "e6fc6b878a1cd74d8c7d3f717b6035a960f16123",
          "md5": "e1c6ea2e89f8fbb5903f788d95e3ca42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.133.13+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.10.2+1.21.8"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.7.0+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.0+1.21.9"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.8+1.21.9.jar",
          "url": "filament-1.3.8+1.21.9.jar",
          "size": 3051753,
          "sha512": "b289ff8e255217cf7a8344493e8ee0d59851121ea70b494764eabebd6ebd8ba77c40273677049c50b4af6bcacfaa7dfa0b10edef9045431b8a2cf44105b90c08",
          "sha256": "dea84fe5dbf8afe4605e36545992d0ad9179cdfc8933ddffe8256d23d477434f",
          "sha1": "e6fc6b878a1cd74d8c7d3f717b6035a960f16123",
          "md5": "e1c6ea2e89f8fbb5903f788d95e3ca42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.8+1.21.9-sources.jar",
          "url": "filament-1.3.8+1.21.9-sources.jar",
          "size": 369893,
          "sha512": "bedd08815eb9e1c31dd15b9ec67a6efe177ba099f34404172edad47ca44a550ebf45cbce660fe64fc582f253bd5780f4613687caa6e09c29b238963e4c96b2dc",
          "sha256": "47117e9b9acf13306b203022c783469f144b68cbc02c629b4dc54837a1921148",
          "sha1": "400dac90c63eb7fca932c835122d26d5dc0eefe3",
          "md5": "68db7563feeba9fb82ecc2b49e3c4ea8"
        }
      ]
    }
  ]
}
