{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library-neo",
    "version": "2.0.6-beta.4+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.4+26.2.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.4+26.2.jar",
          "size": 352575,
          "sha512": "c594270a6ecc6bf2d953801150d6817d6699aea4adc672d9a3b8813c669714e74d210515bb5c3f7db4692db5e1601e455da21edb1917283d64af9d4e172a7ea9",
          "sha256": "03e826fd016acba25eca76781fc2ebce298957eb312ed0f929100f83d964f8aa",
          "sha1": "91116ef3c73a5ad414b6393812c3a0122f4b83ac",
          "md5": "cedd34b4f9d92118b1ae06e0e3a9431c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "eu.pb4",
          "module": "polymer-core-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.4+26.2.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.4+26.2.jar",
          "size": 352575,
          "sha512": "c594270a6ecc6bf2d953801150d6817d6699aea4adc672d9a3b8813c669714e74d210515bb5c3f7db4692db5e1601e455da21edb1917283d64af9d4e172a7ea9",
          "sha256": "03e826fd016acba25eca76781fc2ebce298957eb312ed0f929100f83d964f8aa",
          "sha1": "91116ef3c73a5ad414b6393812c3a0122f4b83ac",
          "md5": "cedd34b4f9d92118b1ae06e0e3a9431c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.4+26.2-sources.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.4+26.2-sources.jar",
          "size": 120966,
          "sha512": "34d3ff96cd2509a9ab531b4824be1e4c3fe114ff5090b58c8d4bb6e177a9b84a2ca97419191c70db33595f55afb768128139bc6b1c31f8f3d985b94931a58ed2",
          "sha256": "8d7026fef661d1f9652500f2597b99e98f721249cc8a31ecc50e5cdaa5d6b496",
          "sha1": "f892def584ac9d371aea215ed4c416ea6d5ba043",
          "md5": "20ee6897179d5f0c9451a2047dfa03a4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.4+26.2.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.4+26.2.jar",
          "size": 352575,
          "sha512": "c594270a6ecc6bf2d953801150d6817d6699aea4adc672d9a3b8813c669714e74d210515bb5c3f7db4692db5e1601e455da21edb1917283d64af9d4e172a7ea9",
          "sha256": "03e826fd016acba25eca76781fc2ebce298957eb312ed0f929100f83d964f8aa",
          "sha1": "91116ef3c73a5ad414b6393812c3a0122f4b83ac",
          "md5": "cedd34b4f9d92118b1ae06e0e3a9431c"
        }
      ]
    }
  ]
}
