{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.0.0-beta1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta1+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta1+1.21.11.jar",
          "size": 357741,
          "sha512": "b82e30435583c94e671e8c320aa7116e04532326e9e229332e278eb5ed4a018d9a0aa4f919a756db4496f97fcdc6984a9359754e4aa16f6fd0c4c147af7f4ba2",
          "sha256": "9ca96fe42005c8264d666c18e9d1976fe596e3d9fdbe9ba2d89baa00fb83bc28",
          "sha1": "aaabf1279983c91eaaf3ab6169ce8662fb141af0",
          "md5": "7f6ec8dd46a2a72282762f96b397bb5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta1+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta1+1.21.11.jar",
          "size": 357741,
          "sha512": "b82e30435583c94e671e8c320aa7116e04532326e9e229332e278eb5ed4a018d9a0aa4f919a756db4496f97fcdc6984a9359754e4aa16f6fd0c4c147af7f4ba2",
          "sha256": "9ca96fe42005c8264d666c18e9d1976fe596e3d9fdbe9ba2d89baa00fb83bc28",
          "sha1": "aaabf1279983c91eaaf3ab6169ce8662fb141af0",
          "md5": "7f6ec8dd46a2a72282762f96b397bb5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta1+1.21.11-sources.jar",
          "url": "blockbench-import-library-2.0.0-beta1+1.21.11-sources.jar",
          "size": 123151,
          "sha512": "7e8882a6faefb463b539759e9bdab301d20c3518d2f0e3316745d67a1567b3c6283013d8157b7c7cd79f4b5c65e53556982255be448ee8aa903362c4f4310d56",
          "sha256": "2f9e43bb9f0cd3bea34051782004ea77f7637d9a457bef108da423fdcc150822",
          "sha1": "56bd1939968ebb46f5106c5b7c3c00eb807a4630",
          "md5": "d68ad90a24b3feda9a8ec17901f793f7"
        }
      ]
    }
  ]
}
