{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.14.8-beta.4+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.14.8-beta.4+1.21.1.jar",
          "url": "filament-0.14.8-beta.4+1.21.1.jar",
          "size": 1424599,
          "sha512": "6e850812bf1e992effa504dde085b4510341cb6f2c8709c3dda57ab1dd43f83c1ab97f2b566663361974c655d16203669c941206ce6533f31fddd2b96e325752",
          "sha256": "9edcd43e6030ffa4462dff15a632a6ffc9c576e9be17d183c93fec679b744255",
          "sha1": "ee5dc9fde564ee7bcfc20b3f57393b9da37bb300",
          "md5": "5e6ef2e6feb4890dfeb7e9693d67ed1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.1+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.8-beta.4+1.21.1.jar",
          "url": "filament-0.14.8-beta.4+1.21.1.jar",
          "size": 1424599,
          "sha512": "6e850812bf1e992effa504dde085b4510341cb6f2c8709c3dda57ab1dd43f83c1ab97f2b566663361974c655d16203669c941206ce6533f31fddd2b96e325752",
          "sha256": "9edcd43e6030ffa4462dff15a632a6ffc9c576e9be17d183c93fec679b744255",
          "sha1": "ee5dc9fde564ee7bcfc20b3f57393b9da37bb300",
          "md5": "5e6ef2e6feb4890dfeb7e9693d67ed1f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.8-beta.4+1.21.1-all.jar",
          "url": "filament-0.14.8-beta.4+1.21.1-all.jar",
          "size": 866118,
          "sha512": "d9b61bbbd7a0a1644cd9a380555ea5d78ecb59763f493abf07bbeca81b4057e4b40c48e1fe8078767f80f70043f2b8891cd31fdfed2b6e7cae543e64b5eba1d2",
          "sha256": "b87cda3f5c018f40d31785cd10021ea65ae6017f7aa9a0c18c92897fee70396c",
          "sha1": "a3d4748e5b0bdc4889c1b8ed595b75fea491dcc6",
          "md5": "afc676c6b254138042324d3bb5342a25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.14.8-beta.4+1.21.1-sources.jar",
          "url": "filament-0.14.8-beta.4+1.21.1-sources.jar",
          "size": 216650,
          "sha512": "b28ad3c39a22319f02165d8701b3b7da48530d104a864f55aa1e4216ddaf99c3166cb8e96e393e27d1b802d93efd3236d09063b494d6c7d8ed573d30f9ba6817",
          "sha256": "8b904095dd747c0280435f5dc7e82d958185ff30161d37b9546e73c79887a4a7",
          "sha1": "4796493e986798e8d054b716ac290c1e995563a6",
          "md5": "8ca7e03c23235337122f7134aec08fa2"
        }
      ]
    }
  ]
}
