{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.14.13+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.14.13+1.21.1.jar",
          "url": "filament-0.14.13+1.21.1.jar",
          "size": 1460420,
          "sha512": "7a600b8b3754b66e00bd3c10875d3a57ab9875fd7712dc4cfc256fcf879cd18d0a39dfb0db167dbe51bf2e88f72db229a5e87ef29d02ca5e4dca0a86213cda80",
          "sha256": "3650e091750100397c623949804fba6e1d288a055a972de191a01d757520387a",
          "sha1": "3ad292f0b11596298ca268a41128910a7f696012",
          "md5": "cde072174782dbe65f01042e0100c9fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.6+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.13+1.21.1.jar",
          "url": "filament-0.14.13+1.21.1.jar",
          "size": 1460420,
          "sha512": "7a600b8b3754b66e00bd3c10875d3a57ab9875fd7712dc4cfc256fcf879cd18d0a39dfb0db167dbe51bf2e88f72db229a5e87ef29d02ca5e4dca0a86213cda80",
          "sha256": "3650e091750100397c623949804fba6e1d288a055a972de191a01d757520387a",
          "sha1": "3ad292f0b11596298ca268a41128910a7f696012",
          "md5": "cde072174782dbe65f01042e0100c9fc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.13+1.21.1-all.jar",
          "url": "filament-0.14.13+1.21.1-all.jar",
          "size": 878689,
          "sha512": "68286fca5bee714fe395a3beb448037342a95f5d2ee2776cc1729eaa7a1be33e54a0f69de390d1b5469af1b385c0055e34d4310b19714aaa1ea3300eeec8967c",
          "sha256": "60c201ca1fc5d494e53122850fa212c7976904ed9c0763ff5edef2dd87522fe2",
          "sha1": "80e7301bed7d168354d6faa5b7ab4687b333b793",
          "md5": "f20e874dc2225f13783ec1395d2b7ba0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.14.13+1.21.1-sources.jar",
          "url": "filament-0.14.13+1.21.1-sources.jar",
          "size": 224790,
          "sha512": "d0bc551a11d22cfdcdf7ffab9cc1414e7cf0efaa693d5520a1e968f47e4894a3b0740e4b64a5ab81386049893b5c4ad44ec7ac2203441784cadde09adae48455",
          "sha256": "267fc32a1580a005125057c413fe8422df70c7456f05661af187bff754a4de99",
          "sha1": "02cefc4ce6bafb17aba32343f55612ed95d7173b",
          "md5": "6a2c9738d9b0f644e8b8b80eaee10067"
        }
      ]
    }
  ]
}
