{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.nucleoid",
    "module": "disguiselib",
    "version": "1.3.6+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "disguiselib-1.3.6+1.21.1.jar",
          "url": "disguiselib-1.3.6+1.21.1.jar",
          "size": 39880,
          "sha512": "13b65034a7faa2da7ae2d2a2d8c1dcfb6d7b8998a822e168cda8247944bbc28f28b0bf3e0635fa33d984d9ba99124963ede873c29e05618835b3c79fce172fa2",
          "sha256": "cd1bb0abf5dbf909127d9afc9b2d80543b841d4f93b3b4a330f6b9af6e3ea715",
          "sha1": "6ce78654839d27e257e81f71d1fae37e84e94c30",
          "md5": "c83344e3dec9d2fc5c110f09511b28d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "disguiselib-1.3.6+1.21.1.jar",
          "url": "disguiselib-1.3.6+1.21.1.jar",
          "size": 39880,
          "sha512": "13b65034a7faa2da7ae2d2a2d8c1dcfb6d7b8998a822e168cda8247944bbc28f28b0bf3e0635fa33d984d9ba99124963ede873c29e05618835b3c79fce172fa2",
          "sha256": "cd1bb0abf5dbf909127d9afc9b2d80543b841d4f93b3b4a330f6b9af6e3ea715",
          "sha1": "6ce78654839d27e257e81f71d1fae37e84e94c30",
          "md5": "c83344e3dec9d2fc5c110f09511b28d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "disguiselib-1.3.6+1.21.1-sources.jar",
          "url": "disguiselib-1.3.6+1.21.1-sources.jar",
          "size": 29184,
          "sha512": "e976061b325bc34983f2a2e7865508e66e348413f8f1ff2ab81f1d45def33bf7636354f6c1fc25e206488657bb12d2ab5ec838881799d00b82f123e97c72ee15",
          "sha256": "f143d6e7a228abc3d88c8a37f9ccff329c0b6b2749ed9bc331c81b348a9cb42f",
          "sha1": "166b80206366a7850573ad29dcdd5c0a268f8abb",
          "md5": "61559a71a80c028e8031dacc4b252bcd"
        }
      ]
    }
  ]
}
