{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.14.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.14.1+1.21.1.jar",
          "url": "filament-0.14.1+1.21.1.jar",
          "size": 1403188,
          "sha512": "c3256d3844417193f6a435e11a4bea169a18a9d9fbd82078f346f8a49f2e1980b94e4c8d939783fb0c29dc57721991ff98e2866bfe4b0bd2bcc3adf07f630588",
          "sha256": "a4941b7d7b41f0d6d6ade9e1ccc43ce334d26b830cf722f0c90b651323d877d7",
          "sha1": "683715a72dcbdd1e36debe3ff39c33668e96b641",
          "md5": "8e1461503b2faa18343f109d642e9c7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.1+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.1+1.21.1.jar",
          "url": "filament-0.14.1+1.21.1.jar",
          "size": 1403188,
          "sha512": "c3256d3844417193f6a435e11a4bea169a18a9d9fbd82078f346f8a49f2e1980b94e4c8d939783fb0c29dc57721991ff98e2866bfe4b0bd2bcc3adf07f630588",
          "sha256": "a4941b7d7b41f0d6d6ade9e1ccc43ce334d26b830cf722f0c90b651323d877d7",
          "sha1": "683715a72dcbdd1e36debe3ff39c33668e96b641",
          "md5": "8e1461503b2faa18343f109d642e9c7c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.1+1.21.1-all.jar",
          "url": "filament-0.14.1+1.21.1-all.jar",
          "size": 844884,
          "sha512": "91685c9f8301dd7a911bc567e92bc0532307880c1cb4180ec780a4a36e4d458c71ccc2e0c13979f595ab858cc11c315acb15ea51e2f2c7b119d821c1159d9655",
          "sha256": "22dfbe1ed432466bb8fa2040e6d6be1cbe69e47f21aedeba0f28e0dd4d6c0198",
          "sha1": "b3310d700ff0d5f0715a55fe36a852e6dbf7308e",
          "md5": "04bfa68799409f98f965e06d0ba04bc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.14.1+1.21.1-sources.jar",
          "url": "filament-0.14.1+1.21.1-sources.jar",
          "size": 207952,
          "sha512": "40957f2df8fde370dc74c71918b04b5ea6f987d6fd2c84f45eaab044aeba6f8cfb0659b2edb054f334c41c101e7f685ffcf82b7a4c14689d7924987260167750",
          "sha256": "e625e3e9c90b381ad54040b7a6d384bb8111b0c79810047f151d8c36335faec9",
          "sha1": "62868ec1f929bd9ab008a9e34431fa6654c67a30",
          "md5": "a3b0a34d45a853f5677bab29c5be44e2"
        }
      ]
    }
  ]
}
