{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.12.6+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.12.6+1.21.1.jar",
          "url": "filament-0.12.6+1.21.1.jar",
          "size": 1360902,
          "sha512": "e7a1b22c3ce1c79bdb54ed7bed480b40749b0128733c81f652cc11931ebd08ac5ba5a6c04a4c393a7bc32315f2739d048bfae47fa7fff39bc84617a4f67cde07",
          "sha256": "a7293aee98bb04f96900cd5282f1a6e82d1ea5a863717d182b1bf0b6f2c97b07",
          "sha1": "c4a74a766ad324b32286ba170743df40bcf9ef2f",
          "md5": "44c8add2b3768de6088aeeaa172f475b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.20+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.6+1.21.1.jar",
          "url": "filament-0.12.6+1.21.1.jar",
          "size": 1360902,
          "sha512": "e7a1b22c3ce1c79bdb54ed7bed480b40749b0128733c81f652cc11931ebd08ac5ba5a6c04a4c393a7bc32315f2739d048bfae47fa7fff39bc84617a4f67cde07",
          "sha256": "a7293aee98bb04f96900cd5282f1a6e82d1ea5a863717d182b1bf0b6f2c97b07",
          "sha1": "c4a74a766ad324b32286ba170743df40bcf9ef2f",
          "md5": "44c8add2b3768de6088aeeaa172f475b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.6+1.21.1-all.jar",
          "url": "filament-0.12.6+1.21.1-all.jar",
          "size": 802172,
          "sha512": "90778656a8f8a5e08b9d6bae2cf7c64ab9838bc9513ca8b3cfd0b87dd1676c19f2e1ee03ba3452fed58f2f17bb135f93030ad1e946fefc92cbe54f8fe48aeac5",
          "sha256": "25fdaab5d468c7821e71cd87996f3a57c875240cae4193386a0fcbca98c68028",
          "sha1": "8dffe9ee7e651ced2fe39da46296eee084a072ae",
          "md5": "a9275c799d40a1fbdca85be85aa4ea9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.12.6+1.21.1-sources.jar",
          "url": "filament-0.12.6+1.21.1-sources.jar",
          "size": 190634,
          "sha512": "8f29ebb13b3c2d73a324e0bdc86946f00dc8e1bfa5630bfdeec6c6c59052ba155572279bbf777e268d27ebad493e97689578a4c7aafafc904fae8311aaf84e5a",
          "sha256": "62c38bd7cb72c2cca09afd2e265b0a90a0407c388394b58d01a63c1c733ecc68",
          "sha1": "d3cafdefa4a9431d0be2c26cf129f29fb54bd2df",
          "md5": "1672f41b70a5799fe8640fac337b6e9f"
        }
      ]
    }
  ]
}
