{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.5.1+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.5.1+1.20.1.jar",
          "url": "filament-0.5.1+1.20.1.jar",
          "size": 587560,
          "sha512": "4f36351cd9d405ab6cdc34892417c4f4b5b48234211354b629db951b38724fc19ffb65baee0ab52e4614ae29d8447ab06bed7ad3f80b0f034409eecbbd8ab7ff",
          "sha256": "effcd521304ceeda7ff7f549f7e7d000c79f851370e530028255c1423a33087f",
          "sha1": "db9004d76c6e0883ad52e2e3a4d144bcf8cfcf08",
          "md5": "e227bb5070ee45c68e820d6843754102"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.9+1.20.1"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.5.1+1.20.1.jar",
          "url": "filament-0.5.1+1.20.1.jar",
          "size": 587560,
          "sha512": "4f36351cd9d405ab6cdc34892417c4f4b5b48234211354b629db951b38724fc19ffb65baee0ab52e4614ae29d8447ab06bed7ad3f80b0f034409eecbbd8ab7ff",
          "sha256": "effcd521304ceeda7ff7f549f7e7d000c79f851370e530028255c1423a33087f",
          "sha1": "db9004d76c6e0883ad52e2e3a4d144bcf8cfcf08",
          "md5": "e227bb5070ee45c68e820d6843754102"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.5.1+1.20.1-sources.jar",
          "url": "filament-0.5.1+1.20.1-sources.jar",
          "size": 100430,
          "sha512": "fbf3955dedcdde8a7470338806bf6ca55d524878ebf8baeab7437906ebf0bc6ccd577bf94c06894f9ac05181d508a39355e2c9d58da67c44e23dde27bc45b11c",
          "sha256": "83fd2139164ed36bc03209d99066d40c073b5c2ec737923056e4edf91f7160c7",
          "sha1": "088d8dada5bbf9f8002d81e05b3596f34bae496c",
          "md5": "a37f5a95ebaec20769edafe44eeb1439"
        }
      ]
    }
  ]
}
