{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.9.0+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.9.0+1.21.jar",
          "url": "filament-0.9.0+1.21.jar",
          "size": 926126,
          "sha512": "481f9135e96e4ee87a9a711ad4e6df0c18690446aa2969840108c4332d4945a6ce24ff11594ebb2c5f75934f7eec5c86aefcdb19405d95f29354e7c13bbe650d",
          "sha256": "4af7ffc0295056fbcf1c87d10a7d890a83947682ebd332a5c503d2517348aa1a",
          "sha1": "48719ceaa33abcfe89699b6066d476145cf39f14",
          "md5": "ec42e1cd94f162418b47a244c2ba3762"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.183+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.9.0+1.21.jar",
          "url": "filament-0.9.0+1.21.jar",
          "size": 926126,
          "sha512": "481f9135e96e4ee87a9a711ad4e6df0c18690446aa2969840108c4332d4945a6ce24ff11594ebb2c5f75934f7eec5c86aefcdb19405d95f29354e7c13bbe650d",
          "sha256": "4af7ffc0295056fbcf1c87d10a7d890a83947682ebd332a5c503d2517348aa1a",
          "sha1": "48719ceaa33abcfe89699b6066d476145cf39f14",
          "md5": "ec42e1cd94f162418b47a244c2ba3762"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.9.0+1.21-sources.jar",
          "url": "filament-0.9.0+1.21-sources.jar",
          "size": 166201,
          "sha512": "453c2126ec56ba659edb232f2b9eebc27ff056c56f2cf8cfd94bdf332467478024733efe1a9c8cb381237da922d6c32cc3dfe44fce3614a2a36941ffee3c1f8f",
          "sha256": "adb230c6ab3af3fcf5704095358e498bbb12d58c510073e43382381efedf8c14",
          "sha1": "f00005c98c6064eba54d1325bf2fe49d1033aec4",
          "md5": "a8d8da30de53124f60d60ee32b9a5f7f"
        }
      ]
    }
  ]
}
