{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.17-patch3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.17-patch3+1.21.1.jar",
          "url": "filament-1.3.17-patch3+1.21.1.jar",
          "size": 2853851,
          "sha512": "10dfe27e1c3d19bbd798d294d411a0f12dc88d6ebe5974378e0537d34f0db850bd0d9923356fa012866f69789253b6a6fd64c4bf244c0d6f5e239fcf09aa1795",
          "sha256": "a9ed99d7ecdf8318ca7160c365e525533742edabb658e5805cd383eb5c3291d6",
          "sha1": "8c9cc47c69782bc5ac6a3feeca44372bf561b616",
          "md5": "9bd0b2c678dc7b19a83756b3b27dbbb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.6.1+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.7+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.2+1.21"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "5.14.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.17-patch3+1.21.1.jar",
          "url": "filament-1.3.17-patch3+1.21.1.jar",
          "size": 2853851,
          "sha512": "10dfe27e1c3d19bbd798d294d411a0f12dc88d6ebe5974378e0537d34f0db850bd0d9923356fa012866f69789253b6a6fd64c4bf244c0d6f5e239fcf09aa1795",
          "sha256": "a9ed99d7ecdf8318ca7160c365e525533742edabb658e5805cd383eb5c3291d6",
          "sha1": "8c9cc47c69782bc5ac6a3feeca44372bf561b616",
          "md5": "9bd0b2c678dc7b19a83756b3b27dbbb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.17-patch3+1.21.1-sources.jar",
          "url": "filament-1.3.17-patch3+1.21.1-sources.jar",
          "size": 380514,
          "sha512": "7a0fe358f5f332e463ed8c2124b43b33478056fa25eb15b125a1a2342df28ffc69f2c1bf9545540d6c2634bb1aed5a344f122575d90506a419f84b39ee890e82",
          "sha256": "e3f0fa8d837d76ebad0880e474deb708088a16ef3fc08fb3324f0cd90d34a837",
          "sha1": "fcd328f6cfe769f863292ecc24ffedb8be98664a",
          "md5": "74403ee23fc4cd053975545d7e5e3af1"
        }
      ]
    }
  ]
}
