{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.8.4+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.8.4+1.21.jar",
          "url": "filament-0.8.4+1.21.jar",
          "size": 816898,
          "sha512": "ded48aa405430bb5c38dd2a8fe8e691a6e876329dc533fb4ef5817a51b1e13b4acc470d87ca5c2b63c1186b9f73b0526388a2b15b0a372883f6819623705bb82",
          "sha256": "85a08f01d1efd7af33094d92bcd6d578cb8daadabf5b5a6568489a2f681e904c",
          "sha1": "3c9d35595890ae5d7a82cb9bc26d42c06232760a",
          "md5": "e9bfa4b78a03722ecc127006eef3b8be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.8.4+1.21.jar",
          "url": "filament-0.8.4+1.21.jar",
          "size": 816898,
          "sha512": "ded48aa405430bb5c38dd2a8fe8e691a6e876329dc533fb4ef5817a51b1e13b4acc470d87ca5c2b63c1186b9f73b0526388a2b15b0a372883f6819623705bb82",
          "sha256": "85a08f01d1efd7af33094d92bcd6d578cb8daadabf5b5a6568489a2f681e904c",
          "sha1": "3c9d35595890ae5d7a82cb9bc26d42c06232760a",
          "md5": "e9bfa4b78a03722ecc127006eef3b8be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.8.4+1.21-sources.jar",
          "url": "filament-0.8.4+1.21-sources.jar",
          "size": 133879,
          "sha512": "73ef24337e09d5d113efdfca222139b2fdcbf4c9c127f12b5d2e29d120b7e2e24405ea58971fcd755797ab36c4777c432d08fbd704ca96189202938fe9d01d52",
          "sha256": "4b9106015e769f2b8c8fc1abcec800e0f5de66a6d41868b8e749ee84f3c9cf1c",
          "sha1": "44c1f2354028202548580899328ad1a893f0de14",
          "md5": "2f4114cb9e495d2ce27e1bde8f08fe61"
        }
      ]
    }
  ]
}
