{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.22+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.22+1.21.11.jar",
          "url": "filament-1.3.22+1.21.11.jar",
          "size": 3074197,
          "sha512": "522f0b1a1e56b06224f49c7c84b1ed7906eaa233e4cc4cd7b320c56dda6d4ef29631d87805b7a86e7babaeaae9dc03044ba496fcb359a03cd42e555e68a98805",
          "sha256": "343fcc02f7092a58485f09a88c455e247a389c52381f55b90ba68a403a8392bb",
          "sha1": "d6c621dec740a6774ce12dcb6ef2fce0ca0213d1",
          "md5": "a4f5abd3a630684012881f97a43e7b35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.12.0+1.21.11"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "2.0.0-beta9+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.1+1.21.10"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.22+1.21.11.jar",
          "url": "filament-1.3.22+1.21.11.jar",
          "size": 3074197,
          "sha512": "522f0b1a1e56b06224f49c7c84b1ed7906eaa233e4cc4cd7b320c56dda6d4ef29631d87805b7a86e7babaeaae9dc03044ba496fcb359a03cd42e555e68a98805",
          "sha256": "343fcc02f7092a58485f09a88c455e247a389c52381f55b90ba68a403a8392bb",
          "sha1": "d6c621dec740a6774ce12dcb6ef2fce0ca0213d1",
          "md5": "a4f5abd3a630684012881f97a43e7b35"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.22+1.21.11-sources.jar",
          "url": "filament-1.3.22+1.21.11-sources.jar",
          "size": 367842,
          "sha512": "ac0dfa20ffa6a08be927fa2dbac9df2d8c92d31c9d9b783b4025e5b20706c01f2e5a165f422813df3766e2a1d839d07fbeb117a3bb651fe39964db9f9429c4c9",
          "sha256": "71f68788663a5ded6dfecbe9adf7cb9b0f400c62398dd38733928363d3295a04",
          "sha1": "8be0b797e0ad644c0d52d997599f8f36855171bb",
          "md5": "2bbb733f1e56507a8fede3a97c26b763"
        }
      ]
    }
  ]
}
