{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.10.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.10.3+1.21.1.jar",
          "url": "filament-0.10.3+1.21.1.jar",
          "size": 950375,
          "sha512": "6eb29f44c5f5ab5052dbd8ddc9b2907e830cec8e8083164ed9217717751d70a6ece93974c38ca995a726ecc24617242baab767ae77eddcf87bfff8cf1a7c81ab",
          "sha256": "02b4fad6c7863383639f003ea75b8db97fc18fd28f1b6c9908e04d639d64b246",
          "sha1": "331fa48528b557b4772d4cac6830cea95f96b50c",
          "md5": "f41f591b96abfe637fbd54efa721700d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.13+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.10.3+1.21.1.jar",
          "url": "filament-0.10.3+1.21.1.jar",
          "size": 950375,
          "sha512": "6eb29f44c5f5ab5052dbd8ddc9b2907e830cec8e8083164ed9217717751d70a6ece93974c38ca995a726ecc24617242baab767ae77eddcf87bfff8cf1a7c81ab",
          "sha256": "02b4fad6c7863383639f003ea75b8db97fc18fd28f1b6c9908e04d639d64b246",
          "sha1": "331fa48528b557b4772d4cac6830cea95f96b50c",
          "md5": "f41f591b96abfe637fbd54efa721700d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.10.3+1.21.1-sources.jar",
          "url": "filament-0.10.3+1.21.1-sources.jar",
          "size": 165495,
          "sha512": "48e61724aa0abafbca7e258d1e37bd145859e59fed68f13bc299424dfaa87335eb33aaef5ab919604399391d1ef66b4fc8f7cc9aa83fe3574508232ebdc1aab6",
          "sha256": "fc45ed4c936b70ceb19c117f901b2c846ca6a0a28b0032b9404d44f848258809",
          "sha1": "0c1a4ac4d74c8bff31c94f468ff00d98859d3045",
          "md5": "127cf6f234ba5e0ff4368631d54d498c"
        }
      ]
    }
  ]
}
