{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.0.0-beta6+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta6+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta6+1.21.11.jar",
          "size": 353852,
          "sha512": "f08545b233b7097e5a759165ee9495fba523ca39549d5981e002e923a76bb940af5d12def703e579458a3ff51511b62c7e62b3c0c4a813a24bef7b6a14aeb37c",
          "sha256": "8e73105e7c8162e4bf7e443881f76d787481c78c5b7bf11ec9cad494b628cb79",
          "sha1": "618b7bfe896b510915ee3c4b046266a9c0e5d224",
          "md5": "cfe0dcb428b905e3bf42fce73023d9a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta6+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta6+1.21.11.jar",
          "size": 353852,
          "sha512": "f08545b233b7097e5a759165ee9495fba523ca39549d5981e002e923a76bb940af5d12def703e579458a3ff51511b62c7e62b3c0c4a813a24bef7b6a14aeb37c",
          "sha256": "8e73105e7c8162e4bf7e443881f76d787481c78c5b7bf11ec9cad494b628cb79",
          "sha1": "618b7bfe896b510915ee3c4b046266a9c0e5d224",
          "md5": "cfe0dcb428b905e3bf42fce73023d9a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta6+1.21.11-sources.jar",
          "url": "blockbench-import-library-2.0.0-beta6+1.21.11-sources.jar",
          "size": 121568,
          "sha512": "df49d645b6f8b606665aec9a678bd02266b4a8ff53312a6048375989c6c2c969ba55adba6284b9904f17cb53d11b165708315a8c31a4e37d756586e44034e3ec",
          "sha256": "fff5bd474694cf6359b4f4b5ed49dff39b8dc8bf27154404789a380a83cf13c8",
          "sha1": "8c4d1138193fe4b316578357cfc66b7e3163ce59",
          "md5": "7ceb5bf36359ceeab2c87119798022a6"
        }
      ]
    }
  ]
}
