{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.12.4+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.12.4+1.21.1.jar",
          "url": "filament-0.12.4+1.21.1.jar",
          "size": 1358518,
          "sha512": "d77baf7260f29289b5da1c28d1eae79dfc87c8a574996419a5d9228d81d85a92ffd089738211a019432ec994385045ca2872e0699875237f8cda969cd8c8833e",
          "sha256": "e178550577496da19992af7fd4f8b6df08f6044a081c03131e9c187325aa2867",
          "sha1": "88d638e12a8b0ccbe9bedc9bc3965a69c30c5984",
          "md5": "01f038ebe86a1d972fd39b2e2eaa7c14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.20+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.4+1.21.1.jar",
          "url": "filament-0.12.4+1.21.1.jar",
          "size": 1358518,
          "sha512": "d77baf7260f29289b5da1c28d1eae79dfc87c8a574996419a5d9228d81d85a92ffd089738211a019432ec994385045ca2872e0699875237f8cda969cd8c8833e",
          "sha256": "e178550577496da19992af7fd4f8b6df08f6044a081c03131e9c187325aa2867",
          "sha1": "88d638e12a8b0ccbe9bedc9bc3965a69c30c5984",
          "md5": "01f038ebe86a1d972fd39b2e2eaa7c14"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.4+1.21.1-all.jar",
          "url": "filament-0.12.4+1.21.1-all.jar",
          "size": 799772,
          "sha512": "1ad46912b5dab79d516107cc7312e40599c4dbd7e93e0d80cdcbaaa6625fb6498cdd71e0cbe54626ee91f7cce6831ac43d538b553a1a74582ad88f6368a40eb5",
          "sha256": "7bc25a9f3c2e90a25c37ffbb005cbf9142c29f34be8265338687aa778ccc52c2",
          "sha1": "2f95caa5ddfb3936e4b3b73d513da2f5995e8a14",
          "md5": "7bcaecbb319ffdb079a1f7434f7294a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.12.4+1.21.1-sources.jar",
          "url": "filament-0.12.4+1.21.1-sources.jar",
          "size": 189560,
          "sha512": "bbb08da5c2b316755e62f4cef8b592f52e2feb9ed8c3a34dd80168d688b89688b3f99b7c240a42d2d972cf0631af3529ad9c32fb32a09d377bed330badbeff79",
          "sha256": "a8facf26e0b6cdb87959b980088deb1d619cc2ea2941bc256d2526eec92c3c46",
          "sha1": "befbe09de46e1f68d9e24bb2eca93458189b4b90",
          "md5": "0d6be2ede1ad38dc364bbb2c9eb1129c"
        }
      ]
    }
  ]
}
