{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.15+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.15+1.21.10.jar",
          "url": "filament-1.3.15+1.21.10.jar",
          "size": 3060734,
          "sha512": "61ac079c87c4807ccbde2f582ffef3457c7910aaecc6aac55027b98e7758dd5102bd74c6005148347690b28e1d6129bcc05a3542351b4420ba10f99bf5131a7a",
          "sha256": "3b62be41d6bdd87b2e068ca29e01fced65d6817d191954ee7b52f85fc9591437",
          "sha1": "e9761d9330eaead07dd4a0c307a4a785897c80be",
          "md5": "f990ce00a9207307b4fdd2de94863457"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.10.2+1.21.8"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.7.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.1+1.21.10"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.15+1.21.10.jar",
          "url": "filament-1.3.15+1.21.10.jar",
          "size": 3060734,
          "sha512": "61ac079c87c4807ccbde2f582ffef3457c7910aaecc6aac55027b98e7758dd5102bd74c6005148347690b28e1d6129bcc05a3542351b4420ba10f99bf5131a7a",
          "sha256": "3b62be41d6bdd87b2e068ca29e01fced65d6817d191954ee7b52f85fc9591437",
          "sha1": "e9761d9330eaead07dd4a0c307a4a785897c80be",
          "md5": "f990ce00a9207307b4fdd2de94863457"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.15+1.21.10-sources.jar",
          "url": "filament-1.3.15+1.21.10-sources.jar",
          "size": 373498,
          "sha512": "dab7e3771b4551621d536ef360eb6dd7b90fba1e1e3f4552d942caeab9978df7ccf0e231265b60407f1f02b20ebf16c16d4c5c7ee944bba1e1305f9520cce951",
          "sha256": "c0a39f346a11819d144d4d17376c834de3921d329d8626bd0dfdf95e0b6278de",
          "sha1": "9efa87e6543a05caff555e2c0c6a78e3e9fa4e29",
          "md5": "7eafef8a6ac46ba40f2765ca7e84f405"
        }
      ]
    }
  ]
}
