{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.20+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.20+1.21.11.jar",
          "url": "filament-1.3.20+1.21.11.jar",
          "size": 3071970,
          "sha512": "d589edcf46fb241e0ea6b4f38048ad863127aa76d94b40f5ca0688883b5f445e6f8641fa7e8291062256f0375a5df6bc49990ceb963e57bb6cd7034f4fe4f534",
          "sha256": "c6444aa6998b9f0070cc7e81052daf96dad1116a120b5b85da4fe41cc242573c",
          "sha1": "2ebfbc593453acce8fdee1534bd699bc47c60811",
          "md5": "a4e3de6e2b18079f7e1e5be68191f60f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.10.2+1.21.8"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.8.2+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.1+1.21.10"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.20+1.21.11.jar",
          "url": "filament-1.3.20+1.21.11.jar",
          "size": 3071970,
          "sha512": "d589edcf46fb241e0ea6b4f38048ad863127aa76d94b40f5ca0688883b5f445e6f8641fa7e8291062256f0375a5df6bc49990ceb963e57bb6cd7034f4fe4f534",
          "sha256": "c6444aa6998b9f0070cc7e81052daf96dad1116a120b5b85da4fe41cc242573c",
          "sha1": "2ebfbc593453acce8fdee1534bd699bc47c60811",
          "md5": "a4e3de6e2b18079f7e1e5be68191f60f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.20+1.21.11-sources.jar",
          "url": "filament-1.3.20+1.21.11-sources.jar",
          "size": 367794,
          "sha512": "0753b02aa967f3c025772a9527133b45cad68ad1ecf9d417c899e16487597d4e395a375e11f6c583effbeab051d7d9eebb16e6c737dd0767e912612c0f51ddd3",
          "sha256": "f0f0c8c850d7a4835691e1a6a8a12237fb0fa3135d19694df104a84d0719b0aa",
          "sha1": "6bedd5a08fe3723cb3093626948fe2999af769dc",
          "md5": "da98c09edca2f6a6e15e06976465d27c"
        }
      ]
    }
  ]
}
