{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.4.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.4.0+1.21.11.jar",
          "url": "filament-1.4.0+1.21.11.jar",
          "size": 12999418,
          "sha512": "d40f851abe214c5b91509ab2bc01f794e57731f4603fcca07589ea32aed358777915f72d9621d4de8e083242ef5a14c7da735c35f8878e4c34706ef233d93601",
          "sha256": "fca19d6226491cbf433568aeb261c3499b10f38892ee1d999db8470cc6ad07b9",
          "sha1": "98019ee9595b172dbab2be756abd69de11a5812d",
          "md5": "a6b5a4cc186911ccc779204de5b1e817"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server",
          "version": {
            "requires": "12.1.6"
          }
        },
        {
          "group": "org.eclipse.jetty.ee10.websocket",
          "module": "jetty-ee10-websocket-jakarta-server",
          "version": {
            "requires": "12.1.6"
          }
        },
        {
          "group": "com.github.victools",
          "module": "jsonschema-generator",
          "version": {
            "requires": "4.35.0"
          }
        },
        {
          "group": "com.j2html",
          "module": "j2html",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20231013"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.12.0+1.21.11"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "2.0.2+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.1+1.21.10"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.4.0+1.21.11.jar",
          "url": "filament-1.4.0+1.21.11.jar",
          "size": 12999418,
          "sha512": "d40f851abe214c5b91509ab2bc01f794e57731f4603fcca07589ea32aed358777915f72d9621d4de8e083242ef5a14c7da735c35f8878e4c34706ef233d93601",
          "sha256": "fca19d6226491cbf433568aeb261c3499b10f38892ee1d999db8470cc6ad07b9",
          "sha1": "98019ee9595b172dbab2be756abd69de11a5812d",
          "md5": "a6b5a4cc186911ccc779204de5b1e817"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.4.0+1.21.11-sources.jar",
          "url": "filament-1.4.0+1.21.11-sources.jar",
          "size": 2352019,
          "sha512": "17ac7c2fa032d0a68da0d0ce59bf02888e23e3f758e3d85294742818c77c7e0506dd62d30efad718b6b34fd6360a8d3b9ae96bc8721e21ddccf52da545473122",
          "sha256": "772952167518690237eab89d3b9f4db7db512c8784ad19172bb3fda87dbb8b95",
          "sha1": "0acb5566db59e9d6cc536f6696845f14a21e4c25",
          "md5": "433d40410dd42e8baae41d4980775c8d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.4.0+1.21.11-all.jar",
          "url": "filament-1.4.0+1.21.11-all.jar",
          "size": 11013750,
          "sha512": "508bb490ea129a6a84ec3c669fc3769126e9d374876663f520a77736f4f4531740e4211e92fcd8b7598103c7f624c9c7bb00213c794dc1942292c02deb5ed2a4",
          "sha256": "781d8b12a136d4bf21fa9792c7356b62c04a1cd4c7f7b8ae2a67a40dbe583006",
          "sha1": "facca926db3e608f59ac570d154b3a9a58be6465",
          "md5": "730c1a559b766caacb0c39bf2e95dcc2"
        }
      ]
    }
  ]
}
