{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.5+1.21.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.5+1.21.9.jar",
          "url": "filament-1.3.5+1.21.9.jar",
          "size": 2924352,
          "sha512": "2427d8ec1493b5cde0dba6480019298dfa53f1dee80e8a8b92c62a8c0be217a3e9aca68573742e3080381c617bee4296639340413e69dc95dd0d9ee80f5a40f1",
          "sha256": "3353d64c0f2c7c7677f3a63dcefe7dd012769f4f5b28c77d88f944923e9d7faf",
          "sha1": "7882961ae7544cafc8a05dff01376e994afd85d5",
          "md5": "e047a9f97aa6edc3dbfac6763ed691a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.133.13+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.10.2+1.21.8"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.7.0+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.0+1.21.9"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.5+1.21.9.jar",
          "url": "filament-1.3.5+1.21.9.jar",
          "size": 2924352,
          "sha512": "2427d8ec1493b5cde0dba6480019298dfa53f1dee80e8a8b92c62a8c0be217a3e9aca68573742e3080381c617bee4296639340413e69dc95dd0d9ee80f5a40f1",
          "sha256": "3353d64c0f2c7c7677f3a63dcefe7dd012769f4f5b28c77d88f944923e9d7faf",
          "sha1": "7882961ae7544cafc8a05dff01376e994afd85d5",
          "md5": "e047a9f97aa6edc3dbfac6763ed691a7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.5+1.21.9-all.jar",
          "url": "filament-1.3.5+1.21.9-all.jar",
          "size": 1247595,
          "sha512": "d15c9b6d1ad8398866be9420d87322136b8a0ae9d66058e278e8fde341c379b63a4e3e7f5bd8482a50cb78b1a6a092e66aa7fa4ccdbba2eed287d92845905ee6",
          "sha256": "96aea2887e7c3f7f35f661d64a2053fb24c110038b7f2c59b923f6721ac0ec17",
          "sha1": "9003131679be18b96be336f4edf435412699f30f",
          "md5": "ab1a3859d431e36bbe6a42483c1cab55"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.5+1.21.9-sources.jar",
          "url": "filament-1.3.5+1.21.9-sources.jar",
          "size": 368328,
          "sha512": "6913a8117db01f596206875a46011373f32e6ebf234d523887412ffefe3f347d1fd8169ec745cb37da448954526f2a2ff36e2d41f22e826bb9ddc5d1004aa5b8",
          "sha256": "b49e8d5471df8f26f865d3f07e9ae52be0715eb1f38b885420a9f6289cbfa527",
          "sha1": "6b4171d67161f913e31e187d5c2757edaa9ebc15",
          "md5": "d4fd7d1a30d82b113f0ea8382aff5891"
        }
      ]
    }
  ]
}
