{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.5.0+1.20.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.5.0+1.20.6.jar",
          "url": "filament-0.5.0+1.20.6.jar",
          "size": 590064,
          "sha512": "e8f98d0ddab11f5e5f0ae36c16f6b00586c9384046cc4998beaa4dcd0d3a16fda87e0db20c5cfea6080f8586351b5ec9e2c65a479781f0280adf80dd10b9a111",
          "sha256": "d15ffbc1adfc105560787d3874e0a9a4c87c0d011cb58743e846124426d70378",
          "sha1": "8bbd2635f1e52edcefe91305f30e0fd2b800151d",
          "md5": "147b1c33804b7fa513f97a8b1709a1fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.99.4+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.9+1.20.6"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.5.0+1.20.6.jar",
          "url": "filament-0.5.0+1.20.6.jar",
          "size": 590064,
          "sha512": "e8f98d0ddab11f5e5f0ae36c16f6b00586c9384046cc4998beaa4dcd0d3a16fda87e0db20c5cfea6080f8586351b5ec9e2c65a479781f0280adf80dd10b9a111",
          "sha256": "d15ffbc1adfc105560787d3874e0a9a4c87c0d011cb58743e846124426d70378",
          "sha1": "8bbd2635f1e52edcefe91305f30e0fd2b800151d",
          "md5": "147b1c33804b7fa513f97a8b1709a1fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.5.0+1.20.6-sources.jar",
          "url": "filament-0.5.0+1.20.6-sources.jar",
          "size": 100162,
          "sha512": "d04ef0f6729b806806480ddf2845cd58aa0a85844403691444fae6370a620ed8d86ce8b15210bcd450db0c3b4eaef06b8afb397081888edd52530c301263eb39",
          "sha256": "e19ddf845046d9f174503c34e4b75122831fc12e6f2c61b945843cd3e946073b",
          "sha1": "ae69760be7cf4255e7431834855c2f75c7a5c568",
          "md5": "9764a553fddadcb0647876a693b6287c"
        }
      ]
    }
  ]
}
