{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.0.0-beta8+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta8+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta8+1.21.11.jar",
          "size": 355688,
          "sha512": "1710e6b026509ea9b717ed2b3a3b10287c19c04e2f2191d0202b514785ca6cd9a105b3c914429183887bdf658da69d9384ae11fe6c241608f0e1d3306057025c",
          "sha256": "8a6c1c6bfc3c35080cf9b0f999f0a2f0b8334ef2cc8d3f1179a21744c00a72f4",
          "sha1": "5f2adcc278365e419743b179033a4fdea7c802fa",
          "md5": "8653fe459b32b030ae75596fd433c22e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta8+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta8+1.21.11.jar",
          "size": 355688,
          "sha512": "1710e6b026509ea9b717ed2b3a3b10287c19c04e2f2191d0202b514785ca6cd9a105b3c914429183887bdf658da69d9384ae11fe6c241608f0e1d3306057025c",
          "sha256": "8a6c1c6bfc3c35080cf9b0f999f0a2f0b8334ef2cc8d3f1179a21744c00a72f4",
          "sha1": "5f2adcc278365e419743b179033a4fdea7c802fa",
          "md5": "8653fe459b32b030ae75596fd433c22e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta8+1.21.11-sources.jar",
          "url": "blockbench-import-library-2.0.0-beta8+1.21.11-sources.jar",
          "size": 122000,
          "sha512": "2d9336760b3f83a06a8bda80c7d1ab7974370d9ab65c798e61158595df37ef659567d727d20fcf4271a73f2239167f1e5855ca622bf2e2f4bc9b699655fbd72f",
          "sha256": "d05ab2543e548f9aba775459b756c3e0e6cbcf1b7461481c8def07d86e43cdd0",
          "sha1": "6a74bf6454c43079281df1682ee0888e7f7c37fb",
          "md5": "5567c2503d26bfc6bd1c1ac76e22aaad"
        }
      ]
    }
  ]
}
