{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "DialogUtils",
    "version": "1.3.0+1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "DialogUtils-1.3.0+1.21.6.jar",
          "url": "DialogUtils-1.3.0+1.21.6.jar",
          "size": 405940,
          "sha512": "a26306c1569496b52e0f2ccdaad5794a5e6d25d6d7de46e4bd70c4af4ec24a6a3b583b9e8320793371c2ff6809671a1596c39928aaf72cdf783247d16c9c3a94",
          "sha256": "538afa77dc90382ad4c13915a718953fbc225c03634cb01aff46bc3ed196310d",
          "sha1": "850aab10286fdd5f4d06d1beaa2504783c4165cc",
          "md5": "1be1f68990b90f22ab7ab84a8ee76dee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.127.1+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "map-canvas-api",
          "version": {
            "requires": "0.5.0+1.21.3"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.6.2+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "DialogUtils-1.3.0+1.21.6.jar",
          "url": "DialogUtils-1.3.0+1.21.6.jar",
          "size": 405940,
          "sha512": "a26306c1569496b52e0f2ccdaad5794a5e6d25d6d7de46e4bd70c4af4ec24a6a3b583b9e8320793371c2ff6809671a1596c39928aaf72cdf783247d16c9c3a94",
          "sha256": "538afa77dc90382ad4c13915a718953fbc225c03634cb01aff46bc3ed196310d",
          "sha1": "850aab10286fdd5f4d06d1beaa2504783c4165cc",
          "md5": "1be1f68990b90f22ab7ab84a8ee76dee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DialogUtils-1.3.0+1.21.6-sources.jar",
          "url": "DialogUtils-1.3.0+1.21.6-sources.jar",
          "size": 11635,
          "sha512": "7bd0c62b8f81722ca8a49bce62890abcadb12318ab36699d2996e38b1a96d8463a5d04c15e0307f80495776f994e30064b71c557976b88a8e8e59e05f5ba4881",
          "sha256": "22008d2e6c2bfc7fd24fe4e24957ab7017e5bc7be0ce32b98dec0375b575ca6f",
          "sha1": "e87ee38193447e84baa2c3509539b0a8f4a97685",
          "md5": "608e928907de83273b9b4c9ecfc6e3d3"
        }
      ]
    }
  ]
}
