{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.nucleoid",
    "module": "disguiselib",
    "version": "1.3.9+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "disguiselib-1.3.9+1.21.1.jar",
          "url": "disguiselib-1.3.9+1.21.1.jar",
          "size": 39919,
          "sha512": "f8bc76054e180698ec794b31acea433a2d3f7fac706225cf97c66951a3f8b54ca776068676bea7970fbc924b8a221ae3a4ba17a8668003fc3c24b42ed5230cbe",
          "sha256": "2f301ceef8268b4a9d1b54798924891eb43a0c07f7303411981eaa0c3ffcf03a",
          "sha1": "0135ec1c754d6cf82adc124cbd5e926d366b0436",
          "md5": "4b0359940de74a18b8c97e7eb505512b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "disguiselib-1.3.9+1.21.1.jar",
          "url": "disguiselib-1.3.9+1.21.1.jar",
          "size": 39919,
          "sha512": "f8bc76054e180698ec794b31acea433a2d3f7fac706225cf97c66951a3f8b54ca776068676bea7970fbc924b8a221ae3a4ba17a8668003fc3c24b42ed5230cbe",
          "sha256": "2f301ceef8268b4a9d1b54798924891eb43a0c07f7303411981eaa0c3ffcf03a",
          "sha1": "0135ec1c754d6cf82adc124cbd5e926d366b0436",
          "md5": "4b0359940de74a18b8c97e7eb505512b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "disguiselib-1.3.9+1.21.1-sources.jar",
          "url": "disguiselib-1.3.9+1.21.1-sources.jar",
          "size": 29136,
          "sha512": "3cda575c57d2f1a29b387a11de56640563b3cb182cc99378668d87d768a75cc941d5d71430958144c1b084759645c95ca653f2194f45b15469cfbadcf5cf7e8f",
          "sha256": "68e8282819db42d0590a429f0bb6b07101a03e741dcdaa4f44cc04ed64646f53",
          "sha1": "26122f3ea2a3d506d1b648fe38a7b4a4fdbe6242",
          "md5": "e2fbdcd64396346727c6a46b616407f1"
        }
      ]
    }
  ]
}
