{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.0.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.1+1.21.11.jar",
          "url": "blockbench-import-library-2.0.1+1.21.11.jar",
          "size": 355457,
          "sha512": "a96b79d83ae321705efe3f45dc1aa06ea79733b9d219fc2e0a22a4da5b6cd29a421a780de2d84b9867bddb436f43795825c93b8bc8e70cfdef6e24ab2c75691b",
          "sha256": "04e6c1c78c3a63b42d6e90c41df3be81ea2f8628569a60eec08d00cf775edf5a",
          "sha1": "6350e150659fd5af770bcfa96f7439801ea9c3be",
          "md5": "e9e5950e0afc022559d7cef641b96aa0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.140.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.0.1+1.21.11.jar",
          "url": "blockbench-import-library-2.0.1+1.21.11.jar",
          "size": 355457,
          "sha512": "a96b79d83ae321705efe3f45dc1aa06ea79733b9d219fc2e0a22a4da5b6cd29a421a780de2d84b9867bddb436f43795825c93b8bc8e70cfdef6e24ab2c75691b",
          "sha256": "04e6c1c78c3a63b42d6e90c41df3be81ea2f8628569a60eec08d00cf775edf5a",
          "sha1": "6350e150659fd5af770bcfa96f7439801ea9c3be",
          "md5": "e9e5950e0afc022559d7cef641b96aa0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.1+1.21.11-sources.jar",
          "url": "blockbench-import-library-2.0.1+1.21.11-sources.jar",
          "size": 121885,
          "sha512": "61104bf0cb3eabfcf5103aaf2cb790dc85d742d598582ed672fa13ac1f866c1644c5449be87f803c00009e5ecbb635efb6440d55e043664c243d6620c4e883ba",
          "sha256": "e82bde1550517e94211773f444fe0e2eb83baa0b5b22df7b340f1db27377deab",
          "sha1": "f132b48cf7cf5ef80fac7015e7820fe4c19709d0",
          "md5": "ae888e6230f2203975439a9f1ea47306"
        }
      ]
    }
  ]
}
