{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.6+1.21.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.6+1.21.7.jar",
          "url": "filament-1.3.6+1.21.7.jar",
          "size": 2889063,
          "sha512": "6aca7e24d3ec3b9c2110973f5dcb729ca03f21675a354ae498e98a48784b3086e848bf7f2197f4bb47db2a4fee5d3c5551042e31c9ce6f4cd1bd4ae6124a2510",
          "sha256": "e182eeab8d4a6f05a365ffe3d327620053a57d1c3243a846dabd188937e63721",
          "sha1": "2fe2a54e1deb30d593efb60a7d49a837b32eab7c",
          "md5": "0b8c9abac2008be231cc16cd9000950e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.128.0+1.21.7"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.13.13+1.21.8"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.13.13+1.21.8"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.13.13+1.21.8"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.13.13+1.21.8"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.13.13+1.21.8"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.13.13+1.21.8"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.13.13+1.21.8"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.13.13+1.21.8"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.10.2+1.21.8"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.7.0+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.7.0+1.21.6"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.6+1.21.7.jar",
          "url": "filament-1.3.6+1.21.7.jar",
          "size": 2889063,
          "sha512": "6aca7e24d3ec3b9c2110973f5dcb729ca03f21675a354ae498e98a48784b3086e848bf7f2197f4bb47db2a4fee5d3c5551042e31c9ce6f4cd1bd4ae6124a2510",
          "sha256": "e182eeab8d4a6f05a365ffe3d327620053a57d1c3243a846dabd188937e63721",
          "sha1": "2fe2a54e1deb30d593efb60a7d49a837b32eab7c",
          "md5": "0b8c9abac2008be231cc16cd9000950e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.6+1.21.7-all.jar",
          "url": "filament-1.3.6+1.21.7-all.jar",
          "size": 1243181,
          "sha512": "35ffd691cfe9f9fbd0d04451ccd362e1831e4ef0f7e9a142b0cb779e0e10bc3f0ab51b5d420000cbc47f03646a89cb3a4436a90024a05eb4bed6cd698baece3b",
          "sha256": "8c97fab867389b0d908422cf81dec77a2dd82f4d8d475f124b45c9e103bcfcd9",
          "sha1": "05da18c3676842b1f6045a639146b8adc52c5c01",
          "md5": "be3272cd339a788adc73cbfdb3979d0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.6+1.21.7-sources.jar",
          "url": "filament-1.3.6+1.21.7-sources.jar",
          "size": 367933,
          "sha512": "8a7b2c4c6fe9e6469f9571d8239626883f404411e95a55203f053adf9b9c7448625191377053e890125d1c0e4e296ac67be3f47ad91140c7084e9eab9e3b3c00",
          "sha256": "b6f9eaa5d13b36250d76f2a8a4497db7c0c9bddef6526ac70426195996e080a6",
          "sha1": "909d6b995c25b240d3a7da5a0e774cdbedffab4c",
          "md5": "9ee4aeebd0fd5bd74015ee45d4a6ac56"
        }
      ]
    }
  ]
}
