{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.14.6+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.14.6+1.21.1.jar",
          "url": "filament-0.14.6+1.21.1.jar",
          "size": 1405208,
          "sha512": "0dcc5a360806bdb4f1c8c7f82dc49ce81ce2bbb69ff0957d2ded1a6d24a597918015388c643bcd91bae73ec5f8a2a93ae1514a89864eb3ed2ad1316046dfeaa1",
          "sha256": "39eae3f6c5970617db4fc4cc918f5a216ae1a2cff0058854a74532aa119ae8b9",
          "sha1": "e4729d2e000565e038ddd3ad763ba23c0c5fe3e5",
          "md5": "3ff87f24dbdf1fe09932ce9f6d509220"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.1+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.6+1.21.1.jar",
          "url": "filament-0.14.6+1.21.1.jar",
          "size": 1405208,
          "sha512": "0dcc5a360806bdb4f1c8c7f82dc49ce81ce2bbb69ff0957d2ded1a6d24a597918015388c643bcd91bae73ec5f8a2a93ae1514a89864eb3ed2ad1316046dfeaa1",
          "sha256": "39eae3f6c5970617db4fc4cc918f5a216ae1a2cff0058854a74532aa119ae8b9",
          "sha1": "e4729d2e000565e038ddd3ad763ba23c0c5fe3e5",
          "md5": "3ff87f24dbdf1fe09932ce9f6d509220"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.6+1.21.1-all.jar",
          "url": "filament-0.14.6+1.21.1-all.jar",
          "size": 846894,
          "sha512": "bd9cd6d65bf32a29faf0898d8fdbe02a2dbaa63337e641245340d4fcbbdcda01d649ac0d484dc1b503461ae1cbbbc9870c5c0cb800e216710d37f33272a9d0fc",
          "sha256": "a20b42328e906685d5971b872cfded7c705189f8ad683c97a7f4933a0983159b",
          "sha1": "cc9d6c6ce351391d86047db8129e8e3226f0c2fa",
          "md5": "68658034865e2a73cc78728ad860263e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.14.6+1.21.1-sources.jar",
          "url": "filament-0.14.6+1.21.1-sources.jar",
          "size": 208604,
          "sha512": "cfafa1d26c0ed68e13444f8d9773d14885f31776f74b163a2f589ab7323326354423ddeb0b662183efca338bbacdfb2d5f058c0b7cea647d1a2b04167e4f34d0",
          "sha256": "3677204ccf4e6af57f77c9338db7409b681e1f734d31174ebb5aa77a2bf7cfb0",
          "sha1": "7dc18b348e0772c87401c477fcd15fecde677238",
          "md5": "a2f8ca02718fb1075a8345b5d5d3ae96"
        }
      ]
    }
  ]
}
