{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.14.9+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.14.9+1.21.1.jar",
          "url": "filament-0.14.9+1.21.1.jar",
          "size": 1428285,
          "sha512": "9ae7a9fb9ea3311e99255f5c0eb17abae662b37bd971bf11e408808f841ea32afdc55c55f1b096608830f656e97f85b596c6321eac6b9030af93d471442b8fb4",
          "sha256": "a66d6461b5ea973dfe9750f872e137f73ab07d1a59948e08b667e48406495d4f",
          "sha1": "7211c644e939a6c3dfc042bca78dcc1adbcd2f1a",
          "md5": "af88617e94b132cf3f47efc42feef118"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.1+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.9+1.21.1.jar",
          "url": "filament-0.14.9+1.21.1.jar",
          "size": 1428285,
          "sha512": "9ae7a9fb9ea3311e99255f5c0eb17abae662b37bd971bf11e408808f841ea32afdc55c55f1b096608830f656e97f85b596c6321eac6b9030af93d471442b8fb4",
          "sha256": "a66d6461b5ea973dfe9750f872e137f73ab07d1a59948e08b667e48406495d4f",
          "sha1": "7211c644e939a6c3dfc042bca78dcc1adbcd2f1a",
          "md5": "af88617e94b132cf3f47efc42feef118"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.9+1.21.1-all.jar",
          "url": "filament-0.14.9+1.21.1-all.jar",
          "size": 870261,
          "sha512": "cda5bf7d69e58efda1102a55ea2462f1ac99ab51ba29fbd2c773a9cf32ea1384b1096ba7f388e098f3f6bcbc8fdc1392f4db88c6419cf4018a94eb31cb2dd490",
          "sha256": "587ed4b5cd878f2d18a2e1b73228bc9e5a5243d289f9e27308707cb3c7d43469",
          "sha1": "7942ee4b26214579deaf27f9fc8dcb89ab961b60",
          "md5": "7c46317cd6faee10901e20c7812b25ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.14.9+1.21.1-sources.jar",
          "url": "filament-0.14.9+1.21.1-sources.jar",
          "size": 218663,
          "sha512": "97a3c1ae8ae6b05e714c454dc7eb9be380961d546a579b24ac78ac3c51da3b39d8a6b01490bf7d65058d2029573a8b3cf509a601c12bbb0b100ecd4af9ea4909",
          "sha256": "45edfe50975b6488914d954c7095cc864aa9f9ebc221f8f32400ff61974a2ff5",
          "sha1": "119dd991d8ef929585402964de24551e870bf430",
          "md5": "92fae841636003d3d7b5a24835f8fe34"
        }
      ]
    }
  ]
}
