{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.9.6+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.9.6+1.21.jar",
          "url": "filament-0.9.6+1.21.jar",
          "size": 926778,
          "sha512": "7e917dbc26115a2db92345d65904798f713392275dad02373ebedba69cec3ebea240e4f72c27da88d6e524a5eeb68f2b6d536ce8f7fac70523824b7ae733169d",
          "sha256": "62cc02dd21fbdd3e231ee9e6d1d9b6907e74f844811d5fce99544643ede67028",
          "sha1": "62b4361cd941be8fbab96dbca8e9f3dca47b847b",
          "md5": "0ea8c72387cce3da3239b6e0456cfcf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.9.6+1.21.jar",
          "url": "filament-0.9.6+1.21.jar",
          "size": 926778,
          "sha512": "7e917dbc26115a2db92345d65904798f713392275dad02373ebedba69cec3ebea240e4f72c27da88d6e524a5eeb68f2b6d536ce8f7fac70523824b7ae733169d",
          "sha256": "62cc02dd21fbdd3e231ee9e6d1d9b6907e74f844811d5fce99544643ede67028",
          "sha1": "62b4361cd941be8fbab96dbca8e9f3dca47b847b",
          "md5": "0ea8c72387cce3da3239b6e0456cfcf9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.9.6+1.21-sources.jar",
          "url": "filament-0.9.6+1.21-sources.jar",
          "size": 166499,
          "sha512": "a0fab28615cbe1131ab608755166d7ce9070abcf267e8c5c6e682f60545cffcf8e1d4405aece4ff502e8b3b3c973bc497a264808a91e9509fe42db58c6ef1e6b",
          "sha256": "d5a7ea936632904b8fbbe304f78929e46820f140fcd7c9ee1cac2b6c0a3315d2",
          "sha1": "3b4562fe9d8da85d73eead5ccf86f40bbc7d0349",
          "md5": "744b27fc1269057f97e371a7fa98c44f"
        }
      ]
    }
  ]
}
