{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.7.0+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.7.0+1.21.jar",
          "url": "filament-0.7.0+1.21.jar",
          "size": 628855,
          "sha512": "e9686cd5165402f4d3acc10f6756a2c1881813d4b69763f3db79fd28bc7ce5b46a561d0008d6a38599134a8804393ad4b46727b43f420e56f56ca6cece142538",
          "sha256": "a2552c5e397ec7b13c3340aee47651ddc624683681864080ef0ab7e7e3298352",
          "sha1": "467341193bb672678f1e3d23711d1fad32f5d1b3",
          "md5": "c2983c009237005d13151be8ad674520"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.7.0+1.21.jar",
          "url": "filament-0.7.0+1.21.jar",
          "size": 628855,
          "sha512": "e9686cd5165402f4d3acc10f6756a2c1881813d4b69763f3db79fd28bc7ce5b46a561d0008d6a38599134a8804393ad4b46727b43f420e56f56ca6cece142538",
          "sha256": "a2552c5e397ec7b13c3340aee47651ddc624683681864080ef0ab7e7e3298352",
          "sha1": "467341193bb672678f1e3d23711d1fad32f5d1b3",
          "md5": "c2983c009237005d13151be8ad674520"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.7.0+1.21-sources.jar",
          "url": "filament-0.7.0+1.21-sources.jar",
          "size": 117204,
          "sha512": "11feecf8a57b9daa35de4137b95edba5a0ce858116e878f45cb337c69df09a120d6b8f224db830b6896e88bb9f2519cb449424fcf00f6909cdca4413285e9ff7",
          "sha256": "583756431db2be2adca114fee08f8aafe246116ecd4152d867e63bbdd09e92d5",
          "sha1": "e2c26c7b3c8b03152070992847fb2863237998d3",
          "md5": "d0c6273e9b4df9edd8c8c6e8e28dd624"
        }
      ]
    }
  ]
}
