{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.12.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.12.2+1.21.1.jar",
          "url": "filament-0.12.2+1.21.1.jar",
          "size": 1353277,
          "sha512": "5f3cc005c01543e521c938ec39b38acb861ae2f2836ad549c1416f5bd61b564e8845f6e5505ffd1b304b1e15edd07118621cbec2f02a18fe8c5d89b4cf7dd958",
          "sha256": "f517e1360eb97f3f10dd378796988b01928f74aa3dd9937e6c437955eeb5dc4e",
          "sha1": "ac691f5521b51e78e392508dcf3d61a12df67720",
          "md5": "a00fa187666e67caac56ff1b0783fb13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.20+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.2+1.21.1.jar",
          "url": "filament-0.12.2+1.21.1.jar",
          "size": 1353277,
          "sha512": "5f3cc005c01543e521c938ec39b38acb861ae2f2836ad549c1416f5bd61b564e8845f6e5505ffd1b304b1e15edd07118621cbec2f02a18fe8c5d89b4cf7dd958",
          "sha256": "f517e1360eb97f3f10dd378796988b01928f74aa3dd9937e6c437955eeb5dc4e",
          "sha1": "ac691f5521b51e78e392508dcf3d61a12df67720",
          "md5": "a00fa187666e67caac56ff1b0783fb13"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.2+1.21.1-all.jar",
          "url": "filament-0.12.2+1.21.1-all.jar",
          "size": 794394,
          "sha512": "abc44c97ea044fea56cf24e762afe28c91ef2818df31f51eb9d28f3a983c45b7daf9f2bfb13858bf7e41aecab7d979e562b6b44edbeeecebd6bfc65771124f5c",
          "sha256": "4fc15983d25d7fa5acc206cb68ce69fd6a375a5f16f0eeb033e33345b210e392",
          "sha1": "984106f02766b63a1915d3a8860400f56d42a19e",
          "md5": "b34d26576cc8a93ed0c536958277c89d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.12.2+1.21.1-sources.jar",
          "url": "filament-0.12.2+1.21.1-sources.jar",
          "size": 187859,
          "sha512": "61e791ef0bfce151c8c8d9b0bb7c67edb07a99298e7f407c64b96d59e0da9cb9ec99058bc4b0b718c30e3b6a8b2e82a230e5dc573b87c0b03a8a00015945ce0e",
          "sha256": "249e8c8541f790b6d89db1c926ce5c90fb3cfb702b424e3180339414b40f1b51",
          "sha1": "1405bfd62bee356938eb5b21a73221a332cf3385",
          "md5": "bc2e71eb7dd27acce5eddb4eaf6fff2a"
        }
      ]
    }
  ]
}
