{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.0.0-beta9+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta9+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta9+1.21.11.jar",
          "size": 355712,
          "sha512": "5bd052ff77436e0272f6e2d87cad7223e43c7dbc47fbe7e3102af17bd32eccaca1d0c09527890af266baadfbfa05941e9e31c03c2abcc2a139d59a7abdec6f58",
          "sha256": "bb6760f0cfc82851287783b18d8726503a696c7d90e2c5f5f33b9e182e7a517e",
          "sha1": "1d906166c21965d75d205946d16f4a2191fbd16a",
          "md5": "e4a9d83759579aa8dba9b318ab03e4c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta9+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta9+1.21.11.jar",
          "size": 355712,
          "sha512": "5bd052ff77436e0272f6e2d87cad7223e43c7dbc47fbe7e3102af17bd32eccaca1d0c09527890af266baadfbfa05941e9e31c03c2abcc2a139d59a7abdec6f58",
          "sha256": "bb6760f0cfc82851287783b18d8726503a696c7d90e2c5f5f33b9e182e7a517e",
          "sha1": "1d906166c21965d75d205946d16f4a2191fbd16a",
          "md5": "e4a9d83759579aa8dba9b318ab03e4c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta9+1.21.11-sources.jar",
          "url": "blockbench-import-library-2.0.0-beta9+1.21.11-sources.jar",
          "size": 122026,
          "sha512": "5e549688476093c97e3341bb8f9b90535dece8f46f0067d4ff9af53ae3b549017ea154e778367c62a697c38fcbba5295a26eab23f9564a8eea4d9c74d1d56a8e",
          "sha256": "ac72d0829cfe2b71a6c07d8ba182eb9845ff9a84fd233679bfe6164cbbe71605",
          "sha1": "e63bd864df34d2a310d042919440e0dae29b304a",
          "md5": "ceec0a78b15d90438cb95a475ab404bf"
        }
      ]
    }
  ]
}
