{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library-neo",
    "version": "2.0.6-beta.5+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.5+26.2.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.5+26.2.jar",
          "size": 352553,
          "sha512": "0ca35b42036a7548d2ab6eedf1014e8e856cf2c733a599d6fc52eb3f8f93e18a648d11442ef7d89b814079f05a021187a9f46a1ed8b4acb745783d6f2a83a7b3",
          "sha256": "1516eaafdf267389658acfdf9f2594df999c6590b27d6db1f9315e85ca63840e",
          "sha1": "6814a95e2b54f08ceb15a87c7970c218e3901750",
          "md5": "dc99fef8c08417972bbc86efb9873c1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "eu.pb4",
          "module": "polymer-core-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.5+26.2.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.5+26.2.jar",
          "size": 352553,
          "sha512": "0ca35b42036a7548d2ab6eedf1014e8e856cf2c733a599d6fc52eb3f8f93e18a648d11442ef7d89b814079f05a021187a9f46a1ed8b4acb745783d6f2a83a7b3",
          "sha256": "1516eaafdf267389658acfdf9f2594df999c6590b27d6db1f9315e85ca63840e",
          "sha1": "6814a95e2b54f08ceb15a87c7970c218e3901750",
          "md5": "dc99fef8c08417972bbc86efb9873c1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.5+26.2-sources.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.5+26.2-sources.jar",
          "size": 120946,
          "sha512": "658b81dd04c7549cb7d8dd490ea891cd0a31cd933c4da72426801277e2eb453ccd7400d1567bab3dc124b4955045967e2d788844b57d0cd0eeb1af27d01564cd",
          "sha256": "b578a65cab8916d36366c2e8dfcb7c901042bd8374b5b4e0c4a8a9ef26643b86",
          "sha1": "e4b6cfc786816369f8e4303a126f428d670c5cf9",
          "md5": "52b210b25d717ef018e661ff172c1ca6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.5+26.2.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.5+26.2.jar",
          "size": 352553,
          "sha512": "0ca35b42036a7548d2ab6eedf1014e8e856cf2c733a599d6fc52eb3f8f93e18a648d11442ef7d89b814079f05a021187a9f46a1ed8b4acb745783d6f2a83a7b3",
          "sha256": "1516eaafdf267389658acfdf9f2594df999c6590b27d6db1f9315e85ca63840e",
          "sha1": "6814a95e2b54f08ceb15a87c7970c218e3901750",
          "md5": "dc99fef8c08417972bbc86efb9873c1e"
        }
      ]
    }
  ]
}
