{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.1.3+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.1.3+26.2.jar",
          "url": "blockbench-import-library-2.1.3+26.2.jar",
          "size": 358805,
          "sha512": "41a404d8244624691ea5cfa3b1da9537e3952049b295307bfa56abc9375bb2aa09c67ba532a02eeb0e7d956b86187fea8b5ab63386e08c4ab980c8923ce110a5",
          "sha256": "f228b9c7837dc6a99d3b4382fbfd25973700b9dfc79bb13b2f4c3781fe0d0319",
          "sha1": "820be988006581fda1f748bafdcaa61563670a04",
          "md5": "8c901a5ba0b3ba2e6ca99f249f68a255"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.152.1+26.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.17.0+26.2-rc-2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.17.0+26.2-rc-2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.17.0+26.2-rc-2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.17.0+26.2-rc-2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.17.0+26.2-rc-2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.17.0+26.2-rc-2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.1.3+26.2.jar",
          "url": "blockbench-import-library-2.1.3+26.2.jar",
          "size": 358805,
          "sha512": "41a404d8244624691ea5cfa3b1da9537e3952049b295307bfa56abc9375bb2aa09c67ba532a02eeb0e7d956b86187fea8b5ab63386e08c4ab980c8923ce110a5",
          "sha256": "f228b9c7837dc6a99d3b4382fbfd25973700b9dfc79bb13b2f4c3781fe0d0319",
          "sha1": "820be988006581fda1f748bafdcaa61563670a04",
          "md5": "8c901a5ba0b3ba2e6ca99f249f68a255"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.1.3+26.2-sources.jar",
          "url": "blockbench-import-library-2.1.3+26.2-sources.jar",
          "size": 123040,
          "sha512": "ee850800e681d98c38196830b4ffaabf15316c923ca746dfdc5a37045a0b76ded63a5fa08e0a775e406ddeac028a107633a13cab4b563d68af6b7fda6df7c626",
          "sha256": "2c44b14144c572911b6f4348187d07756c707a36eef04fd0864fedd0255ff2ea",
          "sha1": "7e500de2521bbb24154e7f09e07d35a287a65bf6",
          "md5": "05fe5a2c3dac8588202e74384a3d3b55"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.1.3+26.2.jar",
          "url": "blockbench-import-library-2.1.3+26.2.jar",
          "size": 358805,
          "sha512": "41a404d8244624691ea5cfa3b1da9537e3952049b295307bfa56abc9375bb2aa09c67ba532a02eeb0e7d956b86187fea8b5ab63386e08c4ab980c8923ce110a5",
          "sha256": "f228b9c7837dc6a99d3b4382fbfd25973700b9dfc79bb13b2f4c3781fe0d0319",
          "sha1": "820be988006581fda1f748bafdcaa61563670a04",
          "md5": "8c901a5ba0b3ba2e6ca99f249f68a255"
        }
      ]
    }
  ]
}
