{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.13.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.13.0+1.21.1.jar",
          "url": "filament-0.13.0+1.21.1.jar",
          "size": 1376045,
          "sha512": "9d9df2753319aaf5698ad01e47f71e3e829e3004a63e2593f357912781c029d670d1122469835e7e6fd88dc05ce72a260834d160a3b30da1e95a172ca253444c",
          "sha256": "b86ad28955b46aeff3666d72e728e88992c01ac5cad92137ace6509ab634d808",
          "sha1": "8dc3d472accd7bc9348923929b6136dc25296379",
          "md5": "f2c2f75bc5cb03efdf69a1375628ccfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.20+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.13.0+1.21.1.jar",
          "url": "filament-0.13.0+1.21.1.jar",
          "size": 1376045,
          "sha512": "9d9df2753319aaf5698ad01e47f71e3e829e3004a63e2593f357912781c029d670d1122469835e7e6fd88dc05ce72a260834d160a3b30da1e95a172ca253444c",
          "sha256": "b86ad28955b46aeff3666d72e728e88992c01ac5cad92137ace6509ab634d808",
          "sha1": "8dc3d472accd7bc9348923929b6136dc25296379",
          "md5": "f2c2f75bc5cb03efdf69a1375628ccfb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.13.0+1.21.1-all.jar",
          "url": "filament-0.13.0+1.21.1-all.jar",
          "size": 817696,
          "sha512": "8bc3a6b94c674926ffb61503b3f43d3a23a4315be88106b7bc2bb52044cf380bea0cde8eac51e5e78d286cbd018d0e366514378e862220c107822b5db834cd9b",
          "sha256": "e85c7df50f57fbcb4fd0cdc64b394e3f0ecb92a3b663daa778fab3a627d3d3e2",
          "sha1": "7743c846724d7e02f93ff530c0d6127390d61eba",
          "md5": "8c93c96991dc6fa76297ff2dc1cea1f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.13.0+1.21.1-sources.jar",
          "url": "filament-0.13.0+1.21.1-sources.jar",
          "size": 195862,
          "sha512": "fd8912359b2181f98623709ef0fd8dc615b202b5fbf58e5ad1b554565d3fef590b40ff4e59f43640dc208b05ef13bda9f2bd710499b19d51ab1656a96548962b",
          "sha256": "aa0e247bbe5071ece5473599402fd0a8bec04915a9706f344a55ca54d84e1e35",
          "sha1": "3cb8a69ea8f3730f339e22f5df282762ba0f56bb",
          "md5": "82bfaf72242e975561c3a21826ebce80"
        }
      ]
    }
  ]
}
