{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.nucleoid",
    "module": "disguiselib",
    "version": "1.3.10+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "disguiselib-1.3.10+1.21.1.jar",
          "url": "disguiselib-1.3.10+1.21.1.jar",
          "size": 40985,
          "sha512": "d80cb2e47db21fddc9a77ee504f5738f3d4c19ec93e455616de7f61283e7ad54a50d3bdd71f8d6cd50859c2673ee35e16195976306c29471282addc8cbdd52c9",
          "sha256": "2fbdd3f7196f7ec05b41a230a9564dadd9dae654418e2d71da8b53ebe5f095f4",
          "sha1": "01debf54ad029639c2cd1f80b543e0224bca9604",
          "md5": "aee917c19ab6c9c3866c9631a5e5c172"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "disguiselib-1.3.10+1.21.1.jar",
          "url": "disguiselib-1.3.10+1.21.1.jar",
          "size": 40985,
          "sha512": "d80cb2e47db21fddc9a77ee504f5738f3d4c19ec93e455616de7f61283e7ad54a50d3bdd71f8d6cd50859c2673ee35e16195976306c29471282addc8cbdd52c9",
          "sha256": "2fbdd3f7196f7ec05b41a230a9564dadd9dae654418e2d71da8b53ebe5f095f4",
          "sha1": "01debf54ad029639c2cd1f80b543e0224bca9604",
          "md5": "aee917c19ab6c9c3866c9631a5e5c172"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "disguiselib-1.3.10+1.21.1-sources.jar",
          "url": "disguiselib-1.3.10+1.21.1-sources.jar",
          "size": 29785,
          "sha512": "2418b813b5e2bb2f7ca63ae966a3d912d07d33173640c25b3106e9e1f28c9a70921322f1ef4593ec3c02281651a269cd1489c4971a21788f4af81160cd92aecf",
          "sha256": "0465a7038d48aed0672523cc8ef3c4bcd5530b2048d8b56620759675f2dedf27",
          "sha1": "2dd1b6560c6733590f42829557ca904b1eafe232",
          "md5": "23a27d42844a9ea23fe781ed0c7a7984"
        }
      ]
    }
  ]
}
