{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "1.8.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-1.8.0+1.21.11.jar",
          "url": "blockbench-import-library-1.8.0+1.21.11.jar",
          "size": 354770,
          "sha512": "680afe836e11e0f7c37f4bec784b417dd808114809dd6fe4bfdd64f108269649877949289302c0ef85291a525092e9f426a9f0efd3acb5592cb44f602b283ab5",
          "sha256": "af0918f0cc3d0fc010e5ce328016da34ed509c518cc42c95b0be6b65da99dd0b",
          "sha1": "66ec3768e20586d9c81fe9df8a0ae7056fa57f17",
          "md5": "786d8737190709f05c66ecb6ae73da61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-1.8.0+1.21.11.jar",
          "url": "blockbench-import-library-1.8.0+1.21.11.jar",
          "size": 354770,
          "sha512": "680afe836e11e0f7c37f4bec784b417dd808114809dd6fe4bfdd64f108269649877949289302c0ef85291a525092e9f426a9f0efd3acb5592cb44f602b283ab5",
          "sha256": "af0918f0cc3d0fc010e5ce328016da34ed509c518cc42c95b0be6b65da99dd0b",
          "sha1": "66ec3768e20586d9c81fe9df8a0ae7056fa57f17",
          "md5": "786d8737190709f05c66ecb6ae73da61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-1.8.0+1.21.11-sources.jar",
          "url": "blockbench-import-library-1.8.0+1.21.11-sources.jar",
          "size": 122700,
          "sha512": "388b095472680eb175babce19fb67a8b647bac1a4fee8d55f70edaca071844d05ebceb75837d0ba3cf96d5ebd9c260782aebab70f7841d667db05cb83175869b",
          "sha256": "ccc0cb0539ec4b4be45328f21c476c7deb63830005df08481e94f7527f57bd22",
          "sha1": "4fff6817a3658b7b22d2cb0f7517a9b5377039ae",
          "md5": "d5f2bb73814d57a15d458a43ed413e2e"
        }
      ]
    }
  ]
}
