{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library-neo",
    "version": "2.0.6-beta.2+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.2+26.1.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.2+26.1.jar",
          "size": 352754,
          "sha512": "96c67537db9c0b125a5b644579ba6129aa84b25e750caacc0c1414e706c7d4466fa45120a712975f812c8be4495455e1c4be0466595d865cbfd577d170f76a57",
          "sha256": "9cb7be488891d86d9ca960ff2fbe171d3b4766901d391b823358430d697a34f5",
          "sha1": "23a871becc002436624bb54e05411b3d4948a1a6",
          "md5": "9d60fba7114f5621c398a605fc234d01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "eu.pb4",
          "module": "polymer-core-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.2+26.1.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.2+26.1.jar",
          "size": 352754,
          "sha512": "96c67537db9c0b125a5b644579ba6129aa84b25e750caacc0c1414e706c7d4466fa45120a712975f812c8be4495455e1c4be0466595d865cbfd577d170f76a57",
          "sha256": "9cb7be488891d86d9ca960ff2fbe171d3b4766901d391b823358430d697a34f5",
          "sha1": "23a871becc002436624bb54e05411b3d4948a1a6",
          "md5": "9d60fba7114f5621c398a605fc234d01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.2+26.1-sources.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.2+26.1-sources.jar",
          "size": 121033,
          "sha512": "8daa679776906b86eca665f631235274abeb709087afd9a7a994b3f9154e7a67cae4e5ad02c609d6a52db39f1a5635104a6de736796e3e18f8d7c7c8b516379b",
          "sha256": "ee99ff418381d38a2c1e4482b4812b68a46304ee52eeb55eaf864e4184b309de",
          "sha1": "ad6b85dbf0997201450e9d0b35dc16aaf84ab91d",
          "md5": "2cb8967b2f8fe9577825d387463b16d8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.2+26.1.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.2+26.1.jar",
          "size": 352754,
          "sha512": "96c67537db9c0b125a5b644579ba6129aa84b25e750caacc0c1414e706c7d4466fa45120a712975f812c8be4495455e1c4be0466595d865cbfd577d170f76a57",
          "sha256": "9cb7be488891d86d9ca960ff2fbe171d3b4766901d391b823358430d697a34f5",
          "sha1": "23a871becc002436624bb54e05411b3d4948a1a6",
          "md5": "9d60fba7114f5621c398a605fc234d01"
        }
      ]
    }
  ]
}
