{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.nucleoid",
    "module": "disguiselib",
    "version": "1.3.7+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "disguiselib-1.3.7+1.21.1.jar",
          "url": "disguiselib-1.3.7+1.21.1.jar",
          "size": 39882,
          "sha512": "8edc3d5544b596aaf1e0f69edeff826c99532655b9d3785faf816181c2c1630299b17798fbff26ffb32e24747a48d0e9bd6a1bc61433141fd37ad95554665533",
          "sha256": "59ca848b8b1d366c150d2544c1b833901715fe35d70d1635f60b3039d8a98864",
          "sha1": "cf1d328174aa9000981e3465f6bd5825f809543f",
          "md5": "34371f030500a30f843013001ae550af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "disguiselib-1.3.7+1.21.1.jar",
          "url": "disguiselib-1.3.7+1.21.1.jar",
          "size": 39882,
          "sha512": "8edc3d5544b596aaf1e0f69edeff826c99532655b9d3785faf816181c2c1630299b17798fbff26ffb32e24747a48d0e9bd6a1bc61433141fd37ad95554665533",
          "sha256": "59ca848b8b1d366c150d2544c1b833901715fe35d70d1635f60b3039d8a98864",
          "sha1": "cf1d328174aa9000981e3465f6bd5825f809543f",
          "md5": "34371f030500a30f843013001ae550af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "disguiselib-1.3.7+1.21.1-sources.jar",
          "url": "disguiselib-1.3.7+1.21.1-sources.jar",
          "size": 29117,
          "sha512": "1f5eeff939f018276c9c246d7ec7b7edf6a68e8531442704f71999324bf4a921f0ac7693df7f38ea42a6ef40b4dba541d046cc2a0dd9189aecb919eb8f34a160",
          "sha256": "aaaabed6465600fa3c581f7826150f1bbaf396329629d4165b7ef1b4933cb05d",
          "sha1": "d6f549b756f9ac47d7ec070c6831faaa2540d63e",
          "md5": "38333b43a17ea79db6784d0a9dfc6d1d"
        }
      ]
    }
  ]
}
