{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.9.7+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.9.7+1.21.jar",
          "url": "filament-0.9.7+1.21.jar",
          "size": 953124,
          "sha512": "c65ed1167e9c753eac2c41af89690603c265516abfb963278be76cb16abbe1e3005c5a2063f22cd3dd85de0830a28a2100f3ef2e629eebdc64ff58ad001e863c",
          "sha256": "04325f2fff5aed410d022709924b8c13f61b05d1211148e65c6f0d66d42aff77",
          "sha1": "f1be921ca6c11b879519df1ca0513515a5b3fd8a",
          "md5": "013691cb11ddd18c91737987929348f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.13+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.9.7+1.21.jar",
          "url": "filament-0.9.7+1.21.jar",
          "size": 953124,
          "sha512": "c65ed1167e9c753eac2c41af89690603c265516abfb963278be76cb16abbe1e3005c5a2063f22cd3dd85de0830a28a2100f3ef2e629eebdc64ff58ad001e863c",
          "sha256": "04325f2fff5aed410d022709924b8c13f61b05d1211148e65c6f0d66d42aff77",
          "sha1": "f1be921ca6c11b879519df1ca0513515a5b3fd8a",
          "md5": "013691cb11ddd18c91737987929348f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.9.7+1.21-sources.jar",
          "url": "filament-0.9.7+1.21-sources.jar",
          "size": 166537,
          "sha512": "cc4f926e6c0b37fa149985df1b8d43e7c83ed46d710fcbfd04b5b23511eef52b4e36afbb65b7fed8830b45df77eafec0cd23b6d04e46aa2c59d97d1c04eb0ee2",
          "sha256": "2a06c8031c1d5302e467222c4a52bf9ac745bd602a08c3ccd5726f5b1671d47e",
          "sha1": "0f5cd5604d7497a560f80883e8796b214cddef78",
          "md5": "d921cc59eb3afa8f272752c7b88c1e31"
        }
      ]
    }
  ]
}
