{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.3+1.21.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.3+1.21.9.jar",
          "url": "filament-1.3.3+1.21.9.jar",
          "size": 1893015,
          "sha512": "874527a661f5095d32c92c7b8138df4faf1343aaad8fa046413fbe1ad416800abd68b606c0f33dff82c506cd585cb3f08614d673a8968ad919fd956a49b15057",
          "sha256": "f7d25892a70990863ce11a9663fdbbfc8bc0b57c4a99e1330cf6b419d3141dff",
          "sha1": "28806c97ec83e5726d0e7ea1d934b157db29c867",
          "md5": "9f89e82b2b51e49d4c07b1ba31b01d05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.133.13+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.14.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.10.2+1.21.8"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.6.0+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.0+1.21.9"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.3+1.21.9.jar",
          "url": "filament-1.3.3+1.21.9.jar",
          "size": 1893015,
          "sha512": "874527a661f5095d32c92c7b8138df4faf1343aaad8fa046413fbe1ad416800abd68b606c0f33dff82c506cd585cb3f08614d673a8968ad919fd956a49b15057",
          "sha256": "f7d25892a70990863ce11a9663fdbbfc8bc0b57c4a99e1330cf6b419d3141dff",
          "sha1": "28806c97ec83e5726d0e7ea1d934b157db29c867",
          "md5": "9f89e82b2b51e49d4c07b1ba31b01d05"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.3+1.21.9-all.jar",
          "url": "filament-1.3.3+1.21.9-all.jar",
          "size": 1211464,
          "sha512": "c8f8724f18c300cda11aedb7fbdc5ed58b0d0e9881d42c451151d887bba59ec9033929d75891d3fb9cbd0568ced84de266a0da5811f01e535fa6773c0daa1df9",
          "sha256": "b0368ac32caa5354dd550caaa0714aede2250724a46e90c8cead3966cacf242a",
          "sha1": "542555805428b891c10d2a7183a2d72cf36b0800",
          "md5": "8a5f296ff5cf4197a26e27ba61242f03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.3+1.21.9-sources.jar",
          "url": "filament-1.3.3+1.21.9-sources.jar",
          "size": 355935,
          "sha512": "974d43afab8373aa3fee9b5bb13deb4bd5a50a42bca26cd6e193f27516df934d8bc56c9deb5d91392eb77a309a4a89b167c6cf0868f074cd012809a418971752",
          "sha256": "154e28c6f1a59344dfd7e240aea22a86223cb5e301d4d00bfc9139ee121aded4",
          "sha1": "b237e82128b240dd283a954495d8253cb30c78e3",
          "md5": "ea8c0e7e24363a5bd407e7b00d32a247"
        }
      ]
    }
  ]
}
