{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "DialogUtils",
    "version": "1.3.2+1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "DialogUtils-1.3.2+1.21.6.jar",
          "url": "DialogUtils-1.3.2+1.21.6.jar",
          "size": 405929,
          "sha512": "1cc91b67bed4c159a2cd933e499dc95752d29d1d6679772e1cbae4c499bb6f2eafad12220988fafaa9b8548225ca3b2209e68258ba05b459409a261493ca7702",
          "sha256": "2a7484fe3db4b803313de89f105a31492c2e99ddbf66c8dc703c64c19cdc0560",
          "sha1": "2fe57e079a89d9c9e838274a912f923a5b7c57fd",
          "md5": "f944894b9c19561e6fbdd4365dc366ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.127.1+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "map-canvas-api",
          "version": {
            "requires": "0.5.0+1.21.3"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.6.2+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "DialogUtils-1.3.2+1.21.6.jar",
          "url": "DialogUtils-1.3.2+1.21.6.jar",
          "size": 405929,
          "sha512": "1cc91b67bed4c159a2cd933e499dc95752d29d1d6679772e1cbae4c499bb6f2eafad12220988fafaa9b8548225ca3b2209e68258ba05b459409a261493ca7702",
          "sha256": "2a7484fe3db4b803313de89f105a31492c2e99ddbf66c8dc703c64c19cdc0560",
          "sha1": "2fe57e079a89d9c9e838274a912f923a5b7c57fd",
          "md5": "f944894b9c19561e6fbdd4365dc366ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DialogUtils-1.3.2+1.21.6-sources.jar",
          "url": "DialogUtils-1.3.2+1.21.6-sources.jar",
          "size": 11622,
          "sha512": "59152f6b1d7f0aaaab848f9e33be82d49927a4cb273b1f4ac332a2ddacebc82d43ad1c81106688307a597bbae92fb28ee4ee97f2cb31fb598da73d30dec00a59",
          "sha256": "60381277ad633cb9df8725c7a65f9d797b1f2d718388817f87e65c104ffd9872",
          "sha1": "36753a42d6b66ef124b07ef554a54d4b2fb6fabd",
          "md5": "ffe116e733bd4e39d55a904bf9d2188f"
        }
      ]
    }
  ]
}
