{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.10.7+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.10.7+1.21.1.jar",
          "url": "filament-0.10.7+1.21.1.jar",
          "size": 956379,
          "sha512": "e2d275daea50bad016112f797fc1b87e168b108e3005b6780d916408b1016138b80a066e7c28766cfc87d61d302ff629c7c28f924e46bb593e37cce3dd3e3d81",
          "sha256": "b7ef27c39fade7d341745ab013dd707841fae0e8e16ab516622a14c383d1cb75",
          "sha1": "58ac30e6d14efb51216d2684f92902aa436f7a4c",
          "md5": "8974abf6d38743ce9b2dfa5a54bc0dd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.20+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.10.7+1.21.1.jar",
          "url": "filament-0.10.7+1.21.1.jar",
          "size": 956379,
          "sha512": "e2d275daea50bad016112f797fc1b87e168b108e3005b6780d916408b1016138b80a066e7c28766cfc87d61d302ff629c7c28f924e46bb593e37cce3dd3e3d81",
          "sha256": "b7ef27c39fade7d341745ab013dd707841fae0e8e16ab516622a14c383d1cb75",
          "sha1": "58ac30e6d14efb51216d2684f92902aa436f7a4c",
          "md5": "8974abf6d38743ce9b2dfa5a54bc0dd2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.10.7+1.21.1-sources.jar",
          "url": "filament-0.10.7+1.21.1-sources.jar",
          "size": 167288,
          "sha512": "95267190acac41564c5da05c34614281f076e88d4454bd51c95b346a8e235dff6fbfd61b341c49884101e452726bda15820ec14f908142f91df1b083350919f4",
          "sha256": "246cb3dd3c4516586b75b46d3ac8cd7344eb7ffc997ce1dda63c97a9f3939dec",
          "sha1": "e830b33f3609e9ab1c7935c69ca0f87d2fe175a9",
          "md5": "dce69590c341bef056152ce7288f6163"
        }
      ]
    }
  ]
}
