{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.10.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.10.2+1.21.1.jar",
          "url": "filament-0.10.2+1.21.1.jar",
          "size": 950423,
          "sha512": "d8949a3229d5e7fb9b2bd07d25cdf479562559c4fb8cadb9cd2822d55ccd35f6b91e8933a7e9a4b23e92ab3fa8d84b54623004699f93be135dc7edc95ce494dd",
          "sha256": "46a427f28f98f6b2be39bee104cf79b8ceb520d5a58ab576dd6157c30c7809e0",
          "sha1": "f4168162eea700ad0e85011db203875017973459",
          "md5": "1095ed307680290992e2db5fde918650"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.13+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.10.2+1.21.1.jar",
          "url": "filament-0.10.2+1.21.1.jar",
          "size": 950423,
          "sha512": "d8949a3229d5e7fb9b2bd07d25cdf479562559c4fb8cadb9cd2822d55ccd35f6b91e8933a7e9a4b23e92ab3fa8d84b54623004699f93be135dc7edc95ce494dd",
          "sha256": "46a427f28f98f6b2be39bee104cf79b8ceb520d5a58ab576dd6157c30c7809e0",
          "sha1": "f4168162eea700ad0e85011db203875017973459",
          "md5": "1095ed307680290992e2db5fde918650"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.10.2+1.21.1-sources.jar",
          "url": "filament-0.10.2+1.21.1-sources.jar",
          "size": 165506,
          "sha512": "1b32480592dd6255c903f324511be0e42b4f4b82726e6b7e76cff349f803a515b36651c3350d60a3437396fa20e4a10b5d1ad9bb77d8e86fa03975196a9e4d89",
          "sha256": "b54e7ccf1127b50a680f79d19a536faa97feb9d677f54d18ab7526f4ebf0977b",
          "sha1": "b006746af1eaea3267f078670c5aa89aabeaa78e",
          "md5": "75076ccaa1f837a3651b46d1887fedb2"
        }
      ]
    }
  ]
}
