{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.8.1+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.8.1+1.21.jar",
          "url": "filament-0.8.1+1.21.jar",
          "size": 595951,
          "sha512": "d59ac745dbdd992638630964c27ed4f22e1d3a224327de8dee3e4cdc735757e8bd06246b4c4c564e4ce8d4c1499828cf568d99b49981774f48df90245219b560",
          "sha256": "572715660970c99b036cc45871d9e82d8df7cef2f858b6ecff038d38c62ea6ec",
          "sha1": "fef95be99bbf26abf93fdf2f762dad3c5863479c",
          "md5": "8584c33f847d049f2fd3f5d36b3b8836"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.8.1+1.21.jar",
          "url": "filament-0.8.1+1.21.jar",
          "size": 595951,
          "sha512": "d59ac745dbdd992638630964c27ed4f22e1d3a224327de8dee3e4cdc735757e8bd06246b4c4c564e4ce8d4c1499828cf568d99b49981774f48df90245219b560",
          "sha256": "572715660970c99b036cc45871d9e82d8df7cef2f858b6ecff038d38c62ea6ec",
          "sha1": "fef95be99bbf26abf93fdf2f762dad3c5863479c",
          "md5": "8584c33f847d049f2fd3f5d36b3b8836"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.8.1+1.21-sources.jar",
          "url": "filament-0.8.1+1.21-sources.jar",
          "size": 130391,
          "sha512": "90b0f31adea3110bad1831b8f59e1746bde50e96122833918008c031e004bad9903c71c1a922dacac6f2c2f22440e61926fd480598b301acb5310e95c53e6a91",
          "sha256": "c2856561da45628dd05af6e9c3fe4085496ec927fec5a4d24af636be42aee91d",
          "sha1": "3acc764aefef084306ad3b806d75a24ad5010310",
          "md5": "91f89ca0b9e721e0e3bb61d2db7ff71e"
        }
      ]
    }
  ]
}
