{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.0.0-beta2+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta2+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta2+1.21.11.jar",
          "size": 356752,
          "sha512": "7edbf66e608c29eda3abdd070042881e725d5361988079d1201e75bbdd13687897087d34b6552a7e02fcab958364a9986de4ef87c7605c93e9d55acfc93b89ee",
          "sha256": "b47665624210f2f2b00eed6abd5faee5e6118f94e82f73ff573c6cfd362e3a46",
          "sha1": "d93d275e655a10a8dbfb786c1707e03037b88c76",
          "md5": "32c4c3e8849706270cff7e209b2585a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta2+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta2+1.21.11.jar",
          "size": 356752,
          "sha512": "7edbf66e608c29eda3abdd070042881e725d5361988079d1201e75bbdd13687897087d34b6552a7e02fcab958364a9986de4ef87c7605c93e9d55acfc93b89ee",
          "sha256": "b47665624210f2f2b00eed6abd5faee5e6118f94e82f73ff573c6cfd362e3a46",
          "sha1": "d93d275e655a10a8dbfb786c1707e03037b88c76",
          "md5": "32c4c3e8849706270cff7e209b2585a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta2+1.21.11-sources.jar",
          "url": "blockbench-import-library-2.0.0-beta2+1.21.11-sources.jar",
          "size": 123085,
          "sha512": "19c66da35304e662d6aa2c15a607556594ff0131f2ee61097f64b6830d078e1aef5545a975baa434d5df39586476d14f44c4822a896d30542c5ad6567c251753",
          "sha256": "8b738c8dc2ea372c5061d7d1afed7573947c97124e15a35374e76cf744a75fce",
          "sha1": "1c681a4404582d30a8289233a179bef8c4487636",
          "md5": "f6d6df149743520645da3f613b5bb933"
        }
      ]
    }
  ]
}
