{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.10+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.10+1.21.10.jar",
          "url": "filament-1.3.10+1.21.10.jar",
          "size": 3062780,
          "sha512": "261a73ed5e568412548fde6658867e0aeddb328740ab6690d7e290044ace852fc513488da85f9a960a34727a6051fa99a0aa4b5fce9d6313788ee166c74f25ef",
          "sha256": "4d133abb37c5c60b6ef148a218c54b9acf8b529316a8bbd1efe6a229f504e3d5",
          "sha1": "92db6ccce393f9b73425a51e229f37fbc74d4f21",
          "md5": "b7813d70d46d1a5cb13038f3f248caf4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.10.2+1.21.8"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.7.0+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.1+1.21.10"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.10+1.21.10.jar",
          "url": "filament-1.3.10+1.21.10.jar",
          "size": 3062780,
          "sha512": "261a73ed5e568412548fde6658867e0aeddb328740ab6690d7e290044ace852fc513488da85f9a960a34727a6051fa99a0aa4b5fce9d6313788ee166c74f25ef",
          "sha256": "4d133abb37c5c60b6ef148a218c54b9acf8b529316a8bbd1efe6a229f504e3d5",
          "sha1": "92db6ccce393f9b73425a51e229f37fbc74d4f21",
          "md5": "b7813d70d46d1a5cb13038f3f248caf4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.10+1.21.10-sources.jar",
          "url": "filament-1.3.10+1.21.10-sources.jar",
          "size": 373238,
          "sha512": "2d348d4432f46a0fd8c5b9b5937fcfad6cb48198c7dce6ceb1512059f9babdede223f9d0cba181a91980fb99d5bcf91aa4733fc310d5cad96d1e626aa7dc6136",
          "sha256": "b5121912990380c6357506cd3400464d943d7ef37168b255ccd19144abd165e5",
          "sha1": "4ee92255bf940fe0383a18c473798445737f1df8",
          "md5": "3ab6e8955342b95ddcc96284e949d492"
        }
      ]
    }
  ]
}
