{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.0.0-beta7+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta7+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta7+1.21.11.jar",
          "size": 353889,
          "sha512": "dfc18e5927be1f814e5c357462782f6ca4a0a7a6fb5da0af5b2dfeac2b4f35a3333c76cbf4501ab4d8ee31a5fce07ca4df7dcbfabd4ceee5c1cbfb0976969040",
          "sha256": "6cb921bfca0c7d3583be3deb58d478d6cde61b27f77ec501b846aabc47dfaf63",
          "sha1": "786177fce9b91aabee1c0041f3a0eb4bd494dc5d",
          "md5": "b3130528b6a9462e2e1096796980712c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta7+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta7+1.21.11.jar",
          "size": 353889,
          "sha512": "dfc18e5927be1f814e5c357462782f6ca4a0a7a6fb5da0af5b2dfeac2b4f35a3333c76cbf4501ab4d8ee31a5fce07ca4df7dcbfabd4ceee5c1cbfb0976969040",
          "sha256": "6cb921bfca0c7d3583be3deb58d478d6cde61b27f77ec501b846aabc47dfaf63",
          "sha1": "786177fce9b91aabee1c0041f3a0eb4bd494dc5d",
          "md5": "b3130528b6a9462e2e1096796980712c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta7+1.21.11-sources.jar",
          "url": "blockbench-import-library-2.0.0-beta7+1.21.11-sources.jar",
          "size": 121481,
          "sha512": "c695262ec97edc4a68fca1eb69c81a815baa946fd7beb38c08ff64bc223df827164f911fbb6e9d806c345ee291674da7977a9c78d3c420f147a5b68adf079b28",
          "sha256": "ffa90a91640407a1810064e4c99e4b7d29371b4b40c6f421bc2726caf046624e",
          "sha1": "1b1ea0007078eab64cc83cdb2769170431e7506c",
          "md5": "06e17e57429befefc2857240d3b94c38"
        }
      ]
    }
  ]
}
