{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.17.6+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.17.6+1.21.5.jar",
          "url": "filament-0.17.6+1.21.5.jar",
          "size": 1549248,
          "sha512": "ab344afc029520d9f54d58968ca2f169c957aba13f0f0e0eab0469a338e1ea2cdd51ff8957d666cc29027fb907a7ea3174b9508e43b593469be5b0f3bcd291b7",
          "sha256": "7c6937d2dd7340e2fbe88fa4317266237224b002792f331433ee25eb9e05ee2c",
          "sha1": "11a09def670271301dad67d5b93aa64ab2290c6e",
          "md5": "95128186f38ad591e4e5713647d5fc52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.3+1.21.5"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.12.3+1.21.5"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.12.3+1.21.5"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.12.3+1.21.5"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.12.3+1.21.5"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.12.3+1.21.5"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.12.3+1.21.5"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.12.3+1.21.5"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.3.0+1.21.5"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.6.2+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.17.6+1.21.5.jar",
          "url": "filament-0.17.6+1.21.5.jar",
          "size": 1549248,
          "sha512": "ab344afc029520d9f54d58968ca2f169c957aba13f0f0e0eab0469a338e1ea2cdd51ff8957d666cc29027fb907a7ea3174b9508e43b593469be5b0f3bcd291b7",
          "sha256": "7c6937d2dd7340e2fbe88fa4317266237224b002792f331433ee25eb9e05ee2c",
          "sha1": "11a09def670271301dad67d5b93aa64ab2290c6e",
          "md5": "95128186f38ad591e4e5713647d5fc52"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.17.6+1.21.5-all.jar",
          "url": "filament-0.17.6+1.21.5-all.jar",
          "size": 1007739,
          "sha512": "5d4fbb243b4fcf7e53b66c29899e0cfaec7352b3f2fc4e19accc81bf0619e63aa0fbed53d8771c0ef931a15bca2dae8348063bc7905000c1de23ec4b741f93d1",
          "sha256": "534942cc8020382211630057d32b54569be8f0d3ca0cf4e17fab00c7afdbaf89",
          "sha1": "b6164a47e067e181324e7d206d5c78dabd52623e",
          "md5": "d3aff40d3047c54b9099280ac2bef01b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.17.6+1.21.5-sources.jar",
          "url": "filament-0.17.6+1.21.5-sources.jar",
          "size": 269901,
          "sha512": "35c5acde0bbc7e574c2bd099135852ff0ca43dca5c13381911bfc810a1be29e66e132f2a3fb80147ad608b097750ed1b828fb8ce7a0f4caf0135a3b660ae63d5",
          "sha256": "10e8afef5625a4cbfcd6fff5a5f6fabcb60f632b8731bfa50833259ceb199638",
          "sha1": "dccc2f35030204ce898b92ccef6cf248d55e4e74",
          "md5": "a23ca97c058222dfc1246e70eebd4d68"
        }
      ]
    }
  ]
}
