{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.7.1+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.7.1+1.21.jar",
          "url": "filament-0.7.1+1.21.jar",
          "size": 629936,
          "sha512": "5f8440d905a956fdc1955d44d0b5811d57072d31f92ecb8a0a4caa2bc2ce2f7b0d5097586cd92609119b943ddcf6b64cc08b4638b0bbbc35921cca6aa65144d1",
          "sha256": "c9641f0b11605eaef285eb76a42a66861c212548a188e8e306dfd4750b965a8e",
          "sha1": "daf95b6be13a1e62304aa15abbbcd6ed8eb67490",
          "md5": "8c8b714f6d2864fde61b30d07ea26235"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.7.1+1.21.jar",
          "url": "filament-0.7.1+1.21.jar",
          "size": 629936,
          "sha512": "5f8440d905a956fdc1955d44d0b5811d57072d31f92ecb8a0a4caa2bc2ce2f7b0d5097586cd92609119b943ddcf6b64cc08b4638b0bbbc35921cca6aa65144d1",
          "sha256": "c9641f0b11605eaef285eb76a42a66861c212548a188e8e306dfd4750b965a8e",
          "sha1": "daf95b6be13a1e62304aa15abbbcd6ed8eb67490",
          "md5": "8c8b714f6d2864fde61b30d07ea26235"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.7.1+1.21-sources.jar",
          "url": "filament-0.7.1+1.21-sources.jar",
          "size": 117360,
          "sha512": "e0b034bd17fca378af2ee236b87b3c52decf49753a2184102da4b0cfdbaba6229d53daef47daf435b74e662ff1eccc684686f3a867153194be7e6fedb804232a",
          "sha256": "4c29cd8e3b7b7aa1086bd60765a077281ff09e0504c660d5645ea3057afd5a47",
          "sha1": "e82bd8a458fd0e22c9501ce2544c7962f5031494",
          "md5": "6c5576c293ce71c6817413dccc90b1be"
        }
      ]
    }
  ]
}
