{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "1.8.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-1.8.1+1.21.11.jar",
          "url": "blockbench-import-library-1.8.1+1.21.11.jar",
          "size": 354847,
          "sha512": "d91df8ac9736786e3b0451c5a43b349d5677fe238d785f48fd8a506f820661c9309e31cf4fb5435b70620d9a04cdb1be50bf56c57d683ddb000accb21207c468",
          "sha256": "aafc2cd7666ae9943fecf090113fa2f71b83d760c8d495c92543596d01beeb0f",
          "sha1": "792a7902ea35598a167f5f72a8900b56f5e5bac9",
          "md5": "50160f55073e3acd29cc4659cb7b68c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-1.8.1+1.21.11.jar",
          "url": "blockbench-import-library-1.8.1+1.21.11.jar",
          "size": 354847,
          "sha512": "d91df8ac9736786e3b0451c5a43b349d5677fe238d785f48fd8a506f820661c9309e31cf4fb5435b70620d9a04cdb1be50bf56c57d683ddb000accb21207c468",
          "sha256": "aafc2cd7666ae9943fecf090113fa2f71b83d760c8d495c92543596d01beeb0f",
          "sha1": "792a7902ea35598a167f5f72a8900b56f5e5bac9",
          "md5": "50160f55073e3acd29cc4659cb7b68c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-1.8.1+1.21.11-sources.jar",
          "url": "blockbench-import-library-1.8.1+1.21.11-sources.jar",
          "size": 122719,
          "sha512": "15de38872bc944227af4cc61b25c6b43fded0b4dea60709a6b22010460f49f9f96e4b47315cbe971b2bf2d8782572eb1e0588e9b81aa0c1b92e198588ae6f8f4",
          "sha256": "1d79fd96e86ded313d39cdd798a4ee8d5fa8ce972cdf151a9a77587a7e13d39f",
          "sha1": "65c26cdd73227470387d4a4e0cab4fc54d12b484",
          "md5": "15a249672e6501f6b83d3d0d0259f801"
        }
      ]
    }
  ]
}
