{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.0.3+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.3+1.21.11.jar",
          "url": "blockbench-import-library-2.0.3+1.21.11.jar",
          "size": 355519,
          "sha512": "d95e0f343872a16b23d2e27c8a90c44ce89673b300b4d7bdf1842038bc6b579ba85f01ecdf08aa3a8ed530758aebd85f817805cd6e8f28a24c8467355852cfca",
          "sha256": "b858c48e42901f2eebdf151d49a8c42d9e4402bf3887e9a57f8c1828b5ae07c6",
          "sha1": "666bf8bdd2be73b5b79ac1ddb20dc2e40408c9bf",
          "md5": "012f23fca4a9773d3fea2c9eefea0f8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.140.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.0.3+1.21.11.jar",
          "url": "blockbench-import-library-2.0.3+1.21.11.jar",
          "size": 355519,
          "sha512": "d95e0f343872a16b23d2e27c8a90c44ce89673b300b4d7bdf1842038bc6b579ba85f01ecdf08aa3a8ed530758aebd85f817805cd6e8f28a24c8467355852cfca",
          "sha256": "b858c48e42901f2eebdf151d49a8c42d9e4402bf3887e9a57f8c1828b5ae07c6",
          "sha1": "666bf8bdd2be73b5b79ac1ddb20dc2e40408c9bf",
          "md5": "012f23fca4a9773d3fea2c9eefea0f8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.3+1.21.11-sources.jar",
          "url": "blockbench-import-library-2.0.3+1.21.11-sources.jar",
          "size": 121974,
          "sha512": "b3e38876b03eaa643355d2dce55b031d00456703b10850549020442a34163958e84d3d92a139d6d7f020c61fbfec4dd32e7fc03c63795b5ea832630fb0b8e524",
          "sha256": "c57632ccd574150739edfe8492cde758362cd60b8dffa58e96827005339cfae9",
          "sha1": "d511ed46a1394ecf9ea5ed295ab995e916231439",
          "md5": "4d96c02ece0998ccaec2ca2af8b08019"
        }
      ]
    }
  ]
}
