{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.5.0+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.5.0+1.20.1.jar",
          "url": "filament-0.5.0+1.20.1.jar",
          "size": 584488,
          "sha512": "75120f9994289e866fb5064ac9ef8adb7deb28dea5ecc2b897e16fb7a0fe1f3717eff94dece037b671fbdf2aff32c4863a62d480994fe7e921489db7014c9443",
          "sha256": "b320277e80927c725641904315fc4facca3cf77e7bc5922e4dd5948f4d9ebf28",
          "sha1": "aa94caa5466788b373cddad5e88340125233b66f",
          "md5": "aaf528fe071aca37c192e81a8e4b65ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.5.19+1.20.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.9+1.20.1"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.5.0+1.20.1.jar",
          "url": "filament-0.5.0+1.20.1.jar",
          "size": 584488,
          "sha512": "75120f9994289e866fb5064ac9ef8adb7deb28dea5ecc2b897e16fb7a0fe1f3717eff94dece037b671fbdf2aff32c4863a62d480994fe7e921489db7014c9443",
          "sha256": "b320277e80927c725641904315fc4facca3cf77e7bc5922e4dd5948f4d9ebf28",
          "sha1": "aa94caa5466788b373cddad5e88340125233b66f",
          "md5": "aaf528fe071aca37c192e81a8e4b65ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.5.0+1.20.1-sources.jar",
          "url": "filament-0.5.0+1.20.1-sources.jar",
          "size": 98606,
          "sha512": "650113cc65ee06ba69919ffbe7cf3e5d5aef505d6a990200a20bed4fc5ac5ff5ee74d955085247a87c90051317f5f3caba2434536f7238038454c47372d67b4d",
          "sha256": "85865defa70ba88a2944ff5a6077761e4636e88aa2dc650430428e8db71befbe",
          "sha1": "d795262e75f7eeb1eb48f638b6d16b4f37d3bfe1",
          "md5": "bb1850adc5dcd0f63e695533a59d5754"
        }
      ]
    }
  ]
}
