{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.12.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.12.3+1.21.1.jar",
          "url": "filament-0.12.3+1.21.1.jar",
          "size": 1354372,
          "sha512": "a1189fd9353dc9831adc9ecb39c45abf84c59bce0cd03bf504210aa7c040fc88fb6fa78d7fc8b293b5648fdafd370760f6a2946958e00e93cd7eb16e02f52a2d",
          "sha256": "0ee776b9643e57ea856ecb97d3d7091e489de0c92befefac242ead05968f2349",
          "sha1": "52f02104684087c74ef98b8311a392f98d9385c5",
          "md5": "0e053c6d8f11d94d77464c2c5be91a13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.20+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.3+1.21.1.jar",
          "url": "filament-0.12.3+1.21.1.jar",
          "size": 1354372,
          "sha512": "a1189fd9353dc9831adc9ecb39c45abf84c59bce0cd03bf504210aa7c040fc88fb6fa78d7fc8b293b5648fdafd370760f6a2946958e00e93cd7eb16e02f52a2d",
          "sha256": "0ee776b9643e57ea856ecb97d3d7091e489de0c92befefac242ead05968f2349",
          "sha1": "52f02104684087c74ef98b8311a392f98d9385c5",
          "md5": "0e053c6d8f11d94d77464c2c5be91a13"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.3+1.21.1-all.jar",
          "url": "filament-0.12.3+1.21.1-all.jar",
          "size": 795542,
          "sha512": "da1f464a55e8e1e112bc0dfe4397957e79fc590c88b14554b565617c3fcb7cbdd86deb663136038112b98d2048826ad51ebe58b30ff189773485d2fe4828d3f5",
          "sha256": "61a7497c6e7604083207ada1bae238d1a561cac051a29eb1a93d3675ab07b6a5",
          "sha1": "ee931ed5edf8dd1986a7a93a942b7ef80e36684f",
          "md5": "c04f5b89ceb8c39e90194b4c49b1de18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.12.3+1.21.1-sources.jar",
          "url": "filament-0.12.3+1.21.1-sources.jar",
          "size": 188027,
          "sha512": "80b678a95820d3037a0b00cb9a3fab53f9180b27b11b401cf85093557b7b4535b25d8fd915742981807435b0ae3560c45cfd133578b23a7709cc61327aa06ce9",
          "sha256": "c98f2b8f5e9305062607297b92087ee5dff7852e591fd108d0dd374b44236a00",
          "sha1": "633d0915fd1bd44ad26035769f5647492d28f8f7",
          "md5": "f59940c12cc93e19ed8b842341b2020a"
        }
      ]
    }
  ]
}
