{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.0.0-beta10+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta10+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta10+1.21.11.jar",
          "size": 355719,
          "sha512": "e3e7e4c839afa89f01ee0750732da34b3839a6b6b7ffbae1664185227e14f7d9c26b619a1dd75b29f30a729af0ed939005b42d23ba15260cc6733dfa12a2277c",
          "sha256": "82f51c67dafc864b8cd86a7de0d133011c191bd9679880f0d91e34a9c4004eb3",
          "sha1": "1aaf7cbd1c0586f88d9b75750a83764834441169",
          "md5": "d740648d34d184837f2fe5bfa24f3543"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.1+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta10+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta10+1.21.11.jar",
          "size": 355719,
          "sha512": "e3e7e4c839afa89f01ee0750732da34b3839a6b6b7ffbae1664185227e14f7d9c26b619a1dd75b29f30a729af0ed939005b42d23ba15260cc6733dfa12a2277c",
          "sha256": "82f51c67dafc864b8cd86a7de0d133011c191bd9679880f0d91e34a9c4004eb3",
          "sha1": "1aaf7cbd1c0586f88d9b75750a83764834441169",
          "md5": "d740648d34d184837f2fe5bfa24f3543"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta10+1.21.11-sources.jar",
          "url": "blockbench-import-library-2.0.0-beta10+1.21.11-sources.jar",
          "size": 122022,
          "sha512": "beb07940dab639650af6d22b229d7e66c9d009d366c8432b5295c423f6b81528e8a70dce26543e6d538ffb7310659e78ef52bf7b7ed227f8ad46649ce106100d",
          "sha256": "c361623db7308f4766f488a1c5034100b6cf508150facba68ef2e25b8b6b329d",
          "sha1": "2c691fecff05f4f46f01fd017694a3086e919e43",
          "md5": "358c615ab56c7d827cfa9f70810d3f1f"
        }
      ]
    }
  ]
}
