{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.6.1+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.6.1+1.21.jar",
          "url": "filament-0.6.1+1.21.jar",
          "size": 597354,
          "sha512": "166fb0c8c8ebbbde561e2e0e08032f9d361d5989a1d6a6cad409ba5d4169e850a0ac86099b6217c90f1d468cdf15078f2558463a2d0b149e656d80247f337e11",
          "sha256": "de7726b2793af22bd3adc050f2c4e384df1b4c808f99ab400910f7ee6d2f558a",
          "sha1": "ca766b0144d706ecbf5217222f1869e00af8feb7",
          "md5": "47c19152f07b5f8aa9c7970ae4d31c63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.6.1+1.21.jar",
          "url": "filament-0.6.1+1.21.jar",
          "size": 597354,
          "sha512": "166fb0c8c8ebbbde561e2e0e08032f9d361d5989a1d6a6cad409ba5d4169e850a0ac86099b6217c90f1d468cdf15078f2558463a2d0b149e656d80247f337e11",
          "sha256": "de7726b2793af22bd3adc050f2c4e384df1b4c808f99ab400910f7ee6d2f558a",
          "sha1": "ca766b0144d706ecbf5217222f1869e00af8feb7",
          "md5": "47c19152f07b5f8aa9c7970ae4d31c63"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.6.1+1.21-sources.jar",
          "url": "filament-0.6.1+1.21-sources.jar",
          "size": 108297,
          "sha512": "f2747ca8580d562cdb05a25cd452991a7c46ea36a833c48ebf8a43ada5752fd3f84116b30907af7cbd312ee5f7f6202b02c8f05639907e6ddd6aae912ea48299",
          "sha256": "6de4d88d0a54c209e000f1e27f788afcc0c2f4a79ea8722721bc1b8641705bbf",
          "sha1": "c5e4ed6f074579bad6f94d306ab4e9ee92a821b9",
          "md5": "9acb666e4b10966cb93deb0f86a9a7f0"
        }
      ]
    }
  ]
}
