{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "2.0.0-beta4+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta4+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta4+1.21.11.jar",
          "size": 353754,
          "sha512": "a30132caccc33d153c3932e8343abc052899cca46b504b26c2b44cbb789d8f5eded9892b8c9f55087ed61a789da14553ec891bd82fadd377b3dc7c6fdc0337ee",
          "sha256": "26b6b6fbbf5ca6f38df4539b847c0185a1cc081e526358e3c7b586d8d88f7b80",
          "sha1": "fa276778e99d9416abb75b00bd081f4bb9151f3e",
          "md5": "498337db70c5bf89c1c59dac6ffe0f14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta4+1.21.11.jar",
          "url": "blockbench-import-library-2.0.0-beta4+1.21.11.jar",
          "size": 353754,
          "sha512": "a30132caccc33d153c3932e8343abc052899cca46b504b26c2b44cbb789d8f5eded9892b8c9f55087ed61a789da14553ec891bd82fadd377b3dc7c6fdc0337ee",
          "sha256": "26b6b6fbbf5ca6f38df4539b847c0185a1cc081e526358e3c7b586d8d88f7b80",
          "sha1": "fa276778e99d9416abb75b00bd081f4bb9151f3e",
          "md5": "498337db70c5bf89c1c59dac6ffe0f14"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-2.0.0-beta4+1.21.11-sources.jar",
          "url": "blockbench-import-library-2.0.0-beta4+1.21.11-sources.jar",
          "size": 121513,
          "sha512": "8b0673a75888ce69ce71b20e4bb5267aa15e42de14479a4afc53027453db2935aa3a8de13fd50582bd569df3e2713e57adf534f5e048a33494b4554240bb3bbc",
          "sha256": "17ff8eca133897c7a181885346a29bf0ccc75a6d4cd4dd60c2fd347f6a07c1e2",
          "sha1": "5b1843c67a484107f1647d318971333ae004d49f",
          "md5": "59519b784571e33f84adf38dd1c63a26"
        }
      ]
    }
  ]
}
