{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.17+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.17+1.21.11.jar",
          "url": "filament-1.3.17+1.21.11.jar",
          "size": 3070768,
          "sha512": "6b7bcc8329264c2a8a35d9b320c8ed347161c20d2671bc7dee02ec9941abf49892cb2d99534b011b70057e075b2c094db1befee5186810b4e6d3c528af3ce8fd",
          "sha256": "4eeeead9723291dbefb55fc0b841ec195b348f2a71390d65f7f38fd2bff07650",
          "sha1": "211b088bdd164975815815543cc23a07bef1315a",
          "md5": "eb87fcdb29ac3ccd787b7240bd7cfaa4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.10.2+1.21.8"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.8.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.1+1.21.10"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.17+1.21.11.jar",
          "url": "filament-1.3.17+1.21.11.jar",
          "size": 3070768,
          "sha512": "6b7bcc8329264c2a8a35d9b320c8ed347161c20d2671bc7dee02ec9941abf49892cb2d99534b011b70057e075b2c094db1befee5186810b4e6d3c528af3ce8fd",
          "sha256": "4eeeead9723291dbefb55fc0b841ec195b348f2a71390d65f7f38fd2bff07650",
          "sha1": "211b088bdd164975815815543cc23a07bef1315a",
          "md5": "eb87fcdb29ac3ccd787b7240bd7cfaa4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.17+1.21.11-sources.jar",
          "url": "filament-1.3.17+1.21.11-sources.jar",
          "size": 366944,
          "sha512": "b6e0048122c5830340faf6332ee5e4ebe3cce8b6f485e2cd98cfd6ccfc27375d3bf6e9a9508f429e3a60873f71ab288a8b7a5b77cce9272fc3010ad0bfb0b3d9",
          "sha256": "e5261ebf22196aa8c9c579af1ff8bcf630b602abef80aa8b71ad355ca0eb9eaf",
          "sha1": "7937449fe5f9c33edfcf04030bb170fb09634371",
          "md5": "6f7ae0646fa901e8d98e7978e21d8866"
        }
      ]
    }
  ]
}
