{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.14.12+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.14.12+1.21.1.jar",
          "url": "filament-0.14.12+1.21.1.jar",
          "size": 1452885,
          "sha512": "b9a7d8ae1f81de697464025347c7d6c4ed5b818235119d19c7e5d32a685b8b1597278c246796b0573069c0638e55349cb35f65ecdb160a7a67d931eb521c098f",
          "sha256": "c1f663b2387f515ea73e3dce7b701177076514ac01db62c76b2d3fbff61db049",
          "sha1": "15576a2cc4ac0b5c36146c77744c21cb941b3b53",
          "md5": "7d6626271f3e155db9ec06f62fe86f1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.5+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.12+1.21.1.jar",
          "url": "filament-0.14.12+1.21.1.jar",
          "size": 1452885,
          "sha512": "b9a7d8ae1f81de697464025347c7d6c4ed5b818235119d19c7e5d32a685b8b1597278c246796b0573069c0638e55349cb35f65ecdb160a7a67d931eb521c098f",
          "sha256": "c1f663b2387f515ea73e3dce7b701177076514ac01db62c76b2d3fbff61db049",
          "sha1": "15576a2cc4ac0b5c36146c77744c21cb941b3b53",
          "md5": "7d6626271f3e155db9ec06f62fe86f1f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.12+1.21.1-all.jar",
          "url": "filament-0.14.12+1.21.1-all.jar",
          "size": 878020,
          "sha512": "cb8f04b20ad27897a7c2cc0d735617b1a3f7105d4bab1c169f06fb8136f495d6c57fbdae25388d4a9940c22fc1005c0611e2af2d3b4ba339f175fc39b7fc3ac9",
          "sha256": "cef4f8bfce4e757cdac4e31f5a0b9ac4bd33d864b39656c0a6de317211a7e072",
          "sha1": "83c65c9bd1b77e6a29e1dd17efbeb2b60d77d6de",
          "md5": "9e02cfa17eb4e88cd5dfe7761586278a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.14.12+1.21.1-sources.jar",
          "url": "filament-0.14.12+1.21.1-sources.jar",
          "size": 224521,
          "sha512": "fff78b0755fb106734014618535d427a1d1dd277ba75775912d861e986ea4abe78910acbfb50276a482ad6845edf476c810e4c7b8c02d2776434fb01aea187bd",
          "sha256": "d5e415e6e2f6b09dc34685a0000335e10837f27fc0fe60c4100e78d7fe0f2331",
          "sha1": "398781ffba4f2c5b36e7e539b98ba156c2c05365",
          "md5": "b31321a90514cd04d95f9a7ad668c936"
        }
      ]
    }
  ]
}
