{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.5.1+1.20.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.5.1+1.20.6.jar",
          "url": "filament-0.5.1+1.20.6.jar",
          "size": 593143,
          "sha512": "675c9f34d40f064fc108e8f3a992da724c3f0bd926fd92a2aef2219969b1a25b98984a7aa7ba01a88b50b7e83df8cb572f30b9033d787f5f0db0711b091d8493",
          "sha256": "7e9e76fa52a5c1289cf7a8be954a782fc4aa6f43381d8905fcb11b144d47cbde",
          "sha1": "3730adce40f4816d04d07a741b67e813081da2ed",
          "md5": "95941c0a7157bfba46c97f95ba95c269"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.99.4+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.8.2+1.20.6"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.9+1.20.6"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.5.1+1.20.6.jar",
          "url": "filament-0.5.1+1.20.6.jar",
          "size": 593143,
          "sha512": "675c9f34d40f064fc108e8f3a992da724c3f0bd926fd92a2aef2219969b1a25b98984a7aa7ba01a88b50b7e83df8cb572f30b9033d787f5f0db0711b091d8493",
          "sha256": "7e9e76fa52a5c1289cf7a8be954a782fc4aa6f43381d8905fcb11b144d47cbde",
          "sha1": "3730adce40f4816d04d07a741b67e813081da2ed",
          "md5": "95941c0a7157bfba46c97f95ba95c269"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.5.1+1.20.6-sources.jar",
          "url": "filament-0.5.1+1.20.6-sources.jar",
          "size": 101988,
          "sha512": "a6e9bc75f664564eebd56c432b6ad0f116a1119e658ef84d7be4c500c022debc8f38b08f8b2565f384a323642a05ac5c1f675d5b6672f8e0e32fd629fe54a73a",
          "sha256": "feddcdeb2001b5af05b860ef32cc33b3d5f825ab1fc36902e04408cdd219d5a0",
          "sha1": "fe5cc921b125888a7ea9cd0ec732960881b60543",
          "md5": "635df63b67a521547acbec2f9735a886"
        }
      ]
    }
  ]
}
