{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library-neo",
    "version": "2.0.6-beta.3+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.3+26.1.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.3+26.1.jar",
          "size": 353091,
          "sha512": "b0d5b3ee67ee5f6d15133e58bad8d050f702fb2b754f97a10e2bd1a1e4f60f6e719a78c42b9c689acc6f6b5fdfdf46a55de974d2c65c60facbe43d7155e684dc",
          "sha256": "bd4ec48fad8927d2c92191ed8fcdf5ba903116603a62d557ec028bc7dc0f3a06",
          "sha1": "dbb6f01e5777b5a75d22e341a810d8df93c922c3",
          "md5": "8fa0804018c76175143a9fc9c2f205b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "eu.pb4",
          "module": "polymer-core-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.3+26.1.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.3+26.1.jar",
          "size": 353091,
          "sha512": "b0d5b3ee67ee5f6d15133e58bad8d050f702fb2b754f97a10e2bd1a1e4f60f6e719a78c42b9c689acc6f6b5fdfdf46a55de974d2c65c60facbe43d7155e684dc",
          "sha256": "bd4ec48fad8927d2c92191ed8fcdf5ba903116603a62d557ec028bc7dc0f3a06",
          "sha1": "dbb6f01e5777b5a75d22e341a810d8df93c922c3",
          "md5": "8fa0804018c76175143a9fc9c2f205b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.3+26.1-sources.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.3+26.1-sources.jar",
          "size": 121078,
          "sha512": "3d09f29d0908f53423966f45cb46a729c8a1924105c4e9c40553510791b20f23533e961f8ddb67213718e334e7da2faf5cdc0bdf5717b5b186066561ea087946",
          "sha256": "0a6a479b86550603249d6191a369930e9d019d26b84c18ba067e3aa006242b00",
          "sha1": "90f00f5ff1b6800bc71a4a682d041026cd8cac9b",
          "md5": "4e3c8880d0193d38df723d0e5da0b883"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.6-beta.3+26.1.jar",
          "url": "blockbench-import-library-neo-2.0.6-beta.3+26.1.jar",
          "size": 353091,
          "sha512": "b0d5b3ee67ee5f6d15133e58bad8d050f702fb2b754f97a10e2bd1a1e4f60f6e719a78c42b9c689acc6f6b5fdfdf46a55de974d2c65c60facbe43d7155e684dc",
          "sha256": "bd4ec48fad8927d2c92191ed8fcdf5ba903116603a62d557ec028bc7dc0f3a06",
          "sha1": "dbb6f01e5777b5a75d22e341a810d8df93c922c3",
          "md5": "8fa0804018c76175143a9fc9c2f205b1"
        }
      ]
    }
  ]
}
