{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.9.4+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.9.4+1.21.jar",
          "url": "filament-0.9.4+1.21.jar",
          "size": 926245,
          "sha512": "0df2df3cc2ae4f8ad43001ec5de3e81dce21241d9551fb85ea22a11b88b1e456698c0dd6aebac16759d88dcee1c4bc0e587130770c03dd599fbf707c84c5f7d1",
          "sha256": "bc4144df45a09f89472aa48f0194d710b6dbb1c31d594b48ae1749ebce945d1d",
          "sha1": "efed4274567ca6a858a6789776ce1ee7456f9ae4",
          "md5": "69e567b2e4512a319e937fe65f7afece"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.183+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.9.4+1.21.jar",
          "url": "filament-0.9.4+1.21.jar",
          "size": 926245,
          "sha512": "0df2df3cc2ae4f8ad43001ec5de3e81dce21241d9551fb85ea22a11b88b1e456698c0dd6aebac16759d88dcee1c4bc0e587130770c03dd599fbf707c84c5f7d1",
          "sha256": "bc4144df45a09f89472aa48f0194d710b6dbb1c31d594b48ae1749ebce945d1d",
          "sha1": "efed4274567ca6a858a6789776ce1ee7456f9ae4",
          "md5": "69e567b2e4512a319e937fe65f7afece"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.9.4+1.21-sources.jar",
          "url": "filament-0.9.4+1.21-sources.jar",
          "size": 166280,
          "sha512": "0270ac542fde17bafac74cda1a643417ace2cf4dfdcfe6d9918e0d75cdc69a0c21b0c6951d2d047a8aa35b27f487030daf5e6e0fe6d4ba219ede1cd7e7ff50b3",
          "sha256": "24d37acf36ec7253d13594338d06ed93d266ff4123cf46ac80a1f312394de6d3",
          "sha1": "2aecc6e171b8833ebec0f69f6afbced6b395051c",
          "md5": "bd8ee37dd84795f08aa34d2de9594f78"
        }
      ]
    }
  ]
}
