{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "DialogUtils",
    "version": "1.5.0+1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "DialogUtils-1.5.0+1.21.6.jar",
          "url": "DialogUtils-1.5.0+1.21.6.jar",
          "size": 400721,
          "sha512": "307a673c4a76a01f5216ab8793f9f484c6df6ccfa54cb92c0565ca8bb371acc4572d4fa708156c50bffc5ccb6f82a0fa7ac557cbc21df24fa226d6b4f4284d29",
          "sha256": "246c68528e686634819d0f76d6521e63758bdaba196231b57334499f4052776e",
          "sha1": "c80c5555cb8c76687b6c3ccf4585865710e4f778",
          "md5": "2e40e253258fb84bd1e7f2cd498c9d1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.127.1+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.13.2+1.21.6"
          }
        },
        {
          "group": "eu.pb4",
          "module": "map-canvas-api",
          "version": {
            "requires": "0.5.0+1.21.3"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.6.2+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "DialogUtils-1.5.0+1.21.6.jar",
          "url": "DialogUtils-1.5.0+1.21.6.jar",
          "size": 400721,
          "sha512": "307a673c4a76a01f5216ab8793f9f484c6df6ccfa54cb92c0565ca8bb371acc4572d4fa708156c50bffc5ccb6f82a0fa7ac557cbc21df24fa226d6b4f4284d29",
          "sha256": "246c68528e686634819d0f76d6521e63758bdaba196231b57334499f4052776e",
          "sha1": "c80c5555cb8c76687b6c3ccf4585865710e4f778",
          "md5": "2e40e253258fb84bd1e7f2cd498c9d1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DialogUtils-1.5.0+1.21.6-sources.jar",
          "url": "DialogUtils-1.5.0+1.21.6-sources.jar",
          "size": 9900,
          "sha512": "0f3a6b44bcaa8e647a960224bd738d4fa537d8f8d6f1e7e6a8e85bbc3301458aff3fad565d82a13b5e7b921398dcb263b97cb4d4f9364f7c8540545070f7a5cd",
          "sha256": "b35105d48dbd3f395e078d3f1d24865d06d555a8fdb88c890b5e041da56358aa",
          "sha1": "c2027d1c2203091c25c24ea6d0ab9f1ff80a036f",
          "md5": "71e97d461e324f2b032bdae5ea1bae4b"
        }
      ]
    }
  ]
}
