{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.6.2+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.6.2+1.21.jar",
          "url": "filament-0.6.2+1.21.jar",
          "size": 597355,
          "sha512": "d4f0bcdcd9b2cee1187283c7c809843b32989144e2b4082fee12394fbe5506c2896706cb6253ce71ad94027a4953a739301593e6691e8f80d50a1e9d85c4a7af",
          "sha256": "0bd2c642c39b1b4927b093c48231717bc67b7dd493785131de4212a80b072e89",
          "sha1": "ecce960bc5befb24ca08bb138effc254a81ffe8c",
          "md5": "ba4753ff9192274984a746499e589a88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.6.2+1.21.jar",
          "url": "filament-0.6.2+1.21.jar",
          "size": 597355,
          "sha512": "d4f0bcdcd9b2cee1187283c7c809843b32989144e2b4082fee12394fbe5506c2896706cb6253ce71ad94027a4953a739301593e6691e8f80d50a1e9d85c4a7af",
          "sha256": "0bd2c642c39b1b4927b093c48231717bc67b7dd493785131de4212a80b072e89",
          "sha1": "ecce960bc5befb24ca08bb138effc254a81ffe8c",
          "md5": "ba4753ff9192274984a746499e589a88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.6.2+1.21-sources.jar",
          "url": "filament-0.6.2+1.21-sources.jar",
          "size": 108301,
          "sha512": "d64328e7ad8ace93b4f2c804f647f2b05864cde4f3e85ed822e82f656b5007f001374a8d94eaa3c73f384aaf209cf5d79eafd2b8b41f9e19a713edcd15ecf490",
          "sha256": "50666e50f9cc3d9cae3a2ca3099d78869faee6f4e1cd6961d17c7e65c8706a5c",
          "sha1": "2c49839f8a45041bd8522248d33c9a8f29577e37",
          "md5": "7ddd9b7653eda89b7867632dcc8f5b70"
        }
      ]
    }
  ]
}
