{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.9.11+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.9.11+1.21.jar",
          "url": "filament-0.9.11+1.21.jar",
          "size": 950728,
          "sha512": "c35f746784b522a7b1e8571ef4ff13269857fc8a8bbc3cc7bfe64bd16532a68bcf1d32d4a742475b2aff0b997066cd3a93b138c99729423f2fafd2840ac63046",
          "sha256": "854b0279f0920930f666af327db6d7152807164e4cd4db67b231b47c647b02d2",
          "sha1": "4fc023cb1d27a085d5a6eb85b10359e14be42532",
          "md5": "e57ec0d2e1012203ff35b58ed299967e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.13+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.9.11+1.21.jar",
          "url": "filament-0.9.11+1.21.jar",
          "size": 950728,
          "sha512": "c35f746784b522a7b1e8571ef4ff13269857fc8a8bbc3cc7bfe64bd16532a68bcf1d32d4a742475b2aff0b997066cd3a93b138c99729423f2fafd2840ac63046",
          "sha256": "854b0279f0920930f666af327db6d7152807164e4cd4db67b231b47c647b02d2",
          "sha1": "4fc023cb1d27a085d5a6eb85b10359e14be42532",
          "md5": "e57ec0d2e1012203ff35b58ed299967e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.9.11+1.21-sources.jar",
          "url": "filament-0.9.11+1.21-sources.jar",
          "size": 165941,
          "sha512": "cd0a7b0095efb7abe6a444f5f93fd295c387423f459ac1f4fcdb3d18cf1ec10c6235a1b1da2141330ce17d98e4be4a7e9d2b87d1a0316bd0899f1dc990dfef2e",
          "sha256": "8c362362e28c1472cb16bb228a763f6a760a67f967507f9f4ee9a647e366278a",
          "sha1": "cb9f410e78182aa828ad020656a45dc6951404fe",
          "md5": "931d9fa4d5cb2ff4627375b635a70e82"
        }
      ]
    }
  ]
}
