{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.14.8-beta.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.14.8-beta.1+1.21.1.jar",
          "url": "filament-0.14.8-beta.1+1.21.1.jar",
          "size": 1411618,
          "sha512": "09dea57c7fca6e74b5289a2cb1f37f12b33d564464fe739f789779b22efc35b78c3b20b37728c5c36dd3e2a7e7a07fba58d4d5bc5e3d42ab8ff9d1c0bf045b8f",
          "sha256": "53aff7f620ded1f159def23da879565a15f3f65365937d9e9b1b7dd771bbb442",
          "sha1": "c09323ecbd7044afa09db793bf4528ab4af62bf1",
          "md5": "830f03cbe0381ad37ef0ef7ebe7a6efb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.1+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.8-beta.1+1.21.1.jar",
          "url": "filament-0.14.8-beta.1+1.21.1.jar",
          "size": 1411618,
          "sha512": "09dea57c7fca6e74b5289a2cb1f37f12b33d564464fe739f789779b22efc35b78c3b20b37728c5c36dd3e2a7e7a07fba58d4d5bc5e3d42ab8ff9d1c0bf045b8f",
          "sha256": "53aff7f620ded1f159def23da879565a15f3f65365937d9e9b1b7dd771bbb442",
          "sha1": "c09323ecbd7044afa09db793bf4528ab4af62bf1",
          "md5": "830f03cbe0381ad37ef0ef7ebe7a6efb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.8-beta.1+1.21.1-all.jar",
          "url": "filament-0.14.8-beta.1+1.21.1-all.jar",
          "size": 853172,
          "sha512": "34e774a5fa1a149887faddcb7bb921dbf7390168a483f84e6ee3e34cac078408d426e7d3b9e188c5cc04f0f3ba2577b5b1ab8065f2ec126bf382bfa8e0e1ba9a",
          "sha256": "edd595e97c730ce26308c32fde3283d1f37330fef584f6d3f28e137b752de03f",
          "sha1": "d38524c8847b5db034aacfb888464ca4ab8aba44",
          "md5": "bfde805577971b45cba51185ed933236"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.14.8-beta.1+1.21.1-sources.jar",
          "url": "filament-0.14.8-beta.1+1.21.1-sources.jar",
          "size": 211515,
          "sha512": "076ebb6a15c4a741c6ab430beefb54e32506468eed743118bbec2b7a071f89b7c5e0925a9238b65edc319a369ee7df5e69da96298715bb7931d8037c98213578",
          "sha256": "ed5072092ed207e7aae1aee50f09988f68b40b82e2344d9a9e73402915d9a7c5",
          "sha1": "565278b7ff92a3469290189efa9e72e42676698f",
          "md5": "50ee9469badb2d7d7162e9c3dbe85fd4"
        }
      ]
    }
  ]
}
