{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.11.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.11.1+1.21.1.jar",
          "url": "filament-0.11.1+1.21.1.jar",
          "size": 980947,
          "sha512": "fcc711c03c625b6a67c7177050797752b7dce52458971d598a7a7054a402947bbe7c1c0258e5b750c4a1014ec98777310a5fb6a515a8c3c175125613c6c18389",
          "sha256": "0b7583b1880a5dadfa6acbd889de456e547a6492c219b086c414b9e4aefbd829",
          "sha1": "be4ab213489dc756b2d11271e8b17ae2127a7ba7",
          "md5": "73b621c8f474c8fb793fc2c6e3c85f95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.20+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.11.1+1.21.1.jar",
          "url": "filament-0.11.1+1.21.1.jar",
          "size": 980947,
          "sha512": "fcc711c03c625b6a67c7177050797752b7dce52458971d598a7a7054a402947bbe7c1c0258e5b750c4a1014ec98777310a5fb6a515a8c3c175125613c6c18389",
          "sha256": "0b7583b1880a5dadfa6acbd889de456e547a6492c219b086c414b9e4aefbd829",
          "sha1": "be4ab213489dc756b2d11271e8b17ae2127a7ba7",
          "md5": "73b621c8f474c8fb793fc2c6e3c85f95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.11.1+1.21.1-sources.jar",
          "url": "filament-0.11.1+1.21.1-sources.jar",
          "size": 178212,
          "sha512": "23de9d54234cb51ff95594c820a76f690f835daadba7059240bd27dc7643c42e06bf1b2a92177a32c1129a80d5b3dc8ab47d9737eb1e1981149a86d2cb9d147f",
          "sha256": "5e11e9da78f9bcb6474f414e9edbbc35ecfebf2a660fa0e2d5f24fa8029509c6",
          "sha1": "aafe7fbe72e84feffd2b67e11c1095f9bcffdd1c",
          "md5": "ad7c592f335ccbc75097a621d0d07561"
        }
      ]
    }
  ]
}
