{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.9.1+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.9.1+1.21.jar",
          "url": "filament-0.9.1+1.21.jar",
          "size": 926510,
          "sha512": "33320cc5f8a0421808335f55149b554c0ec53bb0eef331f265b4cdcd16f71d3a485902ca03fd8faf4a3c43b910a2aff244b837aa013ed650971f3dd4d9fecfec",
          "sha256": "46e53550138653c4ae9cbd332eca2b6901038ac7b790d8f0b0ef666da765b6d0",
          "sha1": "0e686d7ae7393a4d0d2f7aa01322d166515cd1f7",
          "md5": "d99648c5511ec52daf1f27d8cd6207bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.183+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.9.1+1.21.jar",
          "url": "filament-0.9.1+1.21.jar",
          "size": 926510,
          "sha512": "33320cc5f8a0421808335f55149b554c0ec53bb0eef331f265b4cdcd16f71d3a485902ca03fd8faf4a3c43b910a2aff244b837aa013ed650971f3dd4d9fecfec",
          "sha256": "46e53550138653c4ae9cbd332eca2b6901038ac7b790d8f0b0ef666da765b6d0",
          "sha1": "0e686d7ae7393a4d0d2f7aa01322d166515cd1f7",
          "md5": "d99648c5511ec52daf1f27d8cd6207bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.9.1+1.21-sources.jar",
          "url": "filament-0.9.1+1.21-sources.jar",
          "size": 166246,
          "sha512": "f524c5a5a07e444f56991ad6ea0a962deea3ceacd8fdecb20b77eb20668b48983211d0c37a404f2d43119cdb8d18e578e9801118b56ace9d9c47402d52e86d4a",
          "sha256": "39267a03968badefed1f1e7193bf7ef8e024300216d355f374bb3f93983abc0e",
          "sha1": "4be3784fab3f8bc661e868d050619539305137d2",
          "md5": "d4d549e967bcfaee7a33a2adb8c7c01c"
        }
      ]
    }
  ]
}
