{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.10.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.10.0+1.21.1.jar",
          "url": "filament-0.10.0+1.21.1.jar",
          "size": 950401,
          "sha512": "d852f1c429fbb12bc8ced902e53d2b53ac43903ee1967bfcc682166fab28a67747ad20d1c6d5bad929696600aa1fb55b06086f332d0e15df2a7ae56620830653",
          "sha256": "5c8b7f060d861d38d50bdfacd2265f343624cb4cfc0a3930d551d61c7e0bdbec",
          "sha1": "7a1da3afbb2a7e2907c7ca6572a6066cf384afcc",
          "md5": "42159985f4bbf51692f205258d18cef7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.13+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.10.0+1.21.1.jar",
          "url": "filament-0.10.0+1.21.1.jar",
          "size": 950401,
          "sha512": "d852f1c429fbb12bc8ced902e53d2b53ac43903ee1967bfcc682166fab28a67747ad20d1c6d5bad929696600aa1fb55b06086f332d0e15df2a7ae56620830653",
          "sha256": "5c8b7f060d861d38d50bdfacd2265f343624cb4cfc0a3930d551d61c7e0bdbec",
          "sha1": "7a1da3afbb2a7e2907c7ca6572a6066cf384afcc",
          "md5": "42159985f4bbf51692f205258d18cef7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.10.0+1.21.1-sources.jar",
          "url": "filament-0.10.0+1.21.1-sources.jar",
          "size": 165497,
          "sha512": "74958954c9f30968b19dd8f6479a950f449982c35f5c1b5c0745c7e16c656eab5136508134ef7fd9308011b2aa14537212e4e84c25a4d0f056fdb431ca63f7ed",
          "sha256": "c93be2b192091cee9dcd44ba473aa450ae6ab3df5aaf58e635e4391dc2567558",
          "sha1": "823d6584cfa43225ac74261d69b02fd047b94b6a",
          "md5": "156456673b40090d1dc70f9d83492d37"
        }
      ]
    }
  ]
}
