{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.9.3+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.9.3+1.21.jar",
          "url": "filament-0.9.3+1.21.jar",
          "size": 926581,
          "sha512": "13f0175d12e91d2df128ce5c7288a5ee5a5fec6ee02f741d3edf8691332a7ae183ca9846e8bd7d77b025cfd01fd14e2eaee8f8ab78f270b3d7cf6bec57fab56f",
          "sha256": "16d4c1d119696578f0194456246897e935dfacc200f8e1515a1db28aa3ec6c3b",
          "sha1": "e27b5ae467bd9b4d75a01d72b6a862c32bc467e8",
          "md5": "6910ef94c0beb7ef45a924d47f02cde2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.183+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.16+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.9.3+1.21.jar",
          "url": "filament-0.9.3+1.21.jar",
          "size": 926581,
          "sha512": "13f0175d12e91d2df128ce5c7288a5ee5a5fec6ee02f741d3edf8691332a7ae183ca9846e8bd7d77b025cfd01fd14e2eaee8f8ab78f270b3d7cf6bec57fab56f",
          "sha256": "16d4c1d119696578f0194456246897e935dfacc200f8e1515a1db28aa3ec6c3b",
          "sha1": "e27b5ae467bd9b4d75a01d72b6a862c32bc467e8",
          "md5": "6910ef94c0beb7ef45a924d47f02cde2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.9.3+1.21-sources.jar",
          "url": "filament-0.9.3+1.21-sources.jar",
          "size": 166289,
          "sha512": "423193d4d57cbd0b8ef389f5ace968d309db434f7b8fdacb4a418ae21161bf879327a5560a99796e8807541f3a675caebe701655339949daa5d457ad4d441c86",
          "sha256": "f0675e4f5cd41df480ddb9f1f019c12860e17868d0d66cf1077c861189b551d1",
          "sha1": "c7d18afaa5c9f50611c7dd691c157d1fc6fc86dd",
          "md5": "bb446c1ef7b13ef7e9d67c6205755165"
        }
      ]
    }
  ]
}
