{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.7.5+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.7.5+1.21.jar",
          "url": "filament-0.7.5+1.21.jar",
          "size": 596052,
          "sha512": "ecb51e23b1ee9c83adc1b1a0c27bc867f3f970e72f511699f6b626a613823a86ac4147534e927684446908f5f3e9e9d20eca8ffb65c74a1d67b660dc297d3748",
          "sha256": "ecefb162aaae37cf77a7886c1f3a6012d18bfd7211b3a2c349eaaf1de691e3b4",
          "sha1": "c915c461b489dc1b53c0465afa795dc8d95c37cb",
          "md5": "25d29cde8e4c8be6759aaae3f8dbe9d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.7.5+1.21.jar",
          "url": "filament-0.7.5+1.21.jar",
          "size": 596052,
          "sha512": "ecb51e23b1ee9c83adc1b1a0c27bc867f3f970e72f511699f6b626a613823a86ac4147534e927684446908f5f3e9e9d20eca8ffb65c74a1d67b660dc297d3748",
          "sha256": "ecefb162aaae37cf77a7886c1f3a6012d18bfd7211b3a2c349eaaf1de691e3b4",
          "sha1": "c915c461b489dc1b53c0465afa795dc8d95c37cb",
          "md5": "25d29cde8e4c8be6759aaae3f8dbe9d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.7.5+1.21-sources.jar",
          "url": "filament-0.7.5+1.21-sources.jar",
          "size": 130268,
          "sha512": "e1ec809523f1f5df4e9c14c710ead2bb952f5e45f1f2052c3ee4ba4e17ea15ba50bf22cdecc92de0ef98e2af76caeb09574f15620cef4856c48a6dac4dd9466f",
          "sha256": "723b70840c3b5f9d0b90b0d96a9d65c87f4e39fb88ab089519fd8a77c77b4635",
          "sha1": "439410d785c14d04efd001fc3b5db56f325c284b",
          "md5": "9150ac1a1c622ca12f6b5bc7b926a708"
        }
      ]
    }
  ]
}
