{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.9.14+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.9.14+1.21.1.jar",
          "url": "filament-0.9.14+1.21.1.jar",
          "size": 950185,
          "sha512": "e3f8053c29e7810cc45ce9c103878d77eed7ae68bbb96b4ed2aa9fe50b5f11b609c032c0a7e1c3f572035f38c35016f627e5cbc06da8d7fa58a9bbeb8f82711a",
          "sha256": "dcec8c729a0bd50c6535902847e35da21ed922864d7a895a1cfe1febc4c0c020",
          "sha1": "f466d7000498681929f02417311f64fd02d009e5",
          "md5": "a9bf755fcd0136053092fa6f98ae2071"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.13+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.9.14+1.21.1.jar",
          "url": "filament-0.9.14+1.21.1.jar",
          "size": 950185,
          "sha512": "e3f8053c29e7810cc45ce9c103878d77eed7ae68bbb96b4ed2aa9fe50b5f11b609c032c0a7e1c3f572035f38c35016f627e5cbc06da8d7fa58a9bbeb8f82711a",
          "sha256": "dcec8c729a0bd50c6535902847e35da21ed922864d7a895a1cfe1febc4c0c020",
          "sha1": "f466d7000498681929f02417311f64fd02d009e5",
          "md5": "a9bf755fcd0136053092fa6f98ae2071"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.9.14+1.21.1-sources.jar",
          "url": "filament-0.9.14+1.21.1-sources.jar",
          "size": 165373,
          "sha512": "bf92467a653a8ff5b93478f4c0de0e45e5b0824d0cc671a6ba3350d7e8636d090cb8517a9e9c646277d8df5a10ce17b347314c3b16da1482b15e5b83f0fbe059",
          "sha256": "7129b33b5c6c5537162c5c466f0864c15136d74edb055b70bcafd92eb87f6b9d",
          "sha1": "cf59134e0145a2957a8eca601642a101f5419613",
          "md5": "dd317d37623654a2919720accaa8c3ae"
        }
      ]
    }
  ]
}
