{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.7.3+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.7.3+1.21.jar",
          "url": "filament-0.7.3+1.21.jar",
          "size": 633011,
          "sha512": "f75f641b4b150d65bd2f51ba3fab020ac4a8ba5e65ac593fbdf95045c1088d558cd43322267db3c375c0e149359986f17c4e3dfc3e29afb1abde9de64936eeb4",
          "sha256": "cd24a4f63d8ea1094b66ad7294febbf123daa45088621cd9c26faf63897e318e",
          "sha1": "fc4ea1b5077273cdfa9f917dfa8d203c831deb77",
          "md5": "491718fd9748563ad4fe5251e1860fc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.11+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.7.3+1.21.jar",
          "url": "filament-0.7.3+1.21.jar",
          "size": 633011,
          "sha512": "f75f641b4b150d65bd2f51ba3fab020ac4a8ba5e65ac593fbdf95045c1088d558cd43322267db3c375c0e149359986f17c4e3dfc3e29afb1abde9de64936eeb4",
          "sha256": "cd24a4f63d8ea1094b66ad7294febbf123daa45088621cd9c26faf63897e318e",
          "sha1": "fc4ea1b5077273cdfa9f917dfa8d203c831deb77",
          "md5": "491718fd9748563ad4fe5251e1860fc6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.7.3+1.21-sources.jar",
          "url": "filament-0.7.3+1.21-sources.jar",
          "size": 118447,
          "sha512": "e0fb4f244aff358f3485cdc75a88e8173497a6e74a91755876502271ce2985b967d16c6c96d6c7ba377f90efbe2839ee37c522f5976a0bdc6fe19ac125a00633",
          "sha256": "0695510af5ce1f6cff32ae01e9db67dfa9e9e3f3c4f230512e49f474f0b9281d",
          "sha1": "eef31d302ff42ec740933a4019b66eb8beda4b13",
          "md5": "f7cb80f36b478a48312a8b2b59a9a2d5"
        }
      ]
    }
  ]
}
