{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.21+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.21+1.21.11.jar",
          "url": "filament-1.3.21+1.21.11.jar",
          "size": 3071176,
          "sha512": "6b6f43dd7e98d4ac0f1481795cfc7a4541c1a796d75183ffc6adc1e92e0a33c486b757eb84236f7a907f3f474e4bd615b5243cf1114899da08451e8d2bdbf8c3",
          "sha256": "cd6d96c303b4851f4c5175a2a1d5b8ee92cd599bf33901f39f388f03cdd48d89",
          "sha1": "b63549062f02d1f15fdd0d1f5f5b321b092ce9f6",
          "md5": "a456d58c15cdbe53a6662a68d081fa16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.15.0+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.10.2+1.21.8"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "2.0.0-beta7+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.1+1.21.10"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.21+1.21.11.jar",
          "url": "filament-1.3.21+1.21.11.jar",
          "size": 3071176,
          "sha512": "6b6f43dd7e98d4ac0f1481795cfc7a4541c1a796d75183ffc6adc1e92e0a33c486b757eb84236f7a907f3f474e4bd615b5243cf1114899da08451e8d2bdbf8c3",
          "sha256": "cd6d96c303b4851f4c5175a2a1d5b8ee92cd599bf33901f39f388f03cdd48d89",
          "sha1": "b63549062f02d1f15fdd0d1f5f5b321b092ce9f6",
          "md5": "a456d58c15cdbe53a6662a68d081fa16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.21+1.21.11-sources.jar",
          "url": "filament-1.3.21+1.21.11-sources.jar",
          "size": 367824,
          "sha512": "fba7b35bc50438a196853d56c901e0e6d3a1646160ac221ff5511665ed9517c8d3fdbb2fb6c2b44c819dd212d5514b778e91d6af5c0d5129f939e463ae2c7286",
          "sha256": "2044e03e3e601c3f0918423e2d028d322e7e2eb9861f980f870ee677685b7af0",
          "sha1": "8a619cd8b64edc8136500975ab76fdf4a7e143b4",
          "md5": "362a4a57a0299e723a97caf22c2a8ce1"
        }
      ]
    }
  ]
}
