{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.12+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.12+1.21.1.jar",
          "url": "filament-1.3.12+1.21.1.jar",
          "size": 2846641,
          "sha512": "ab5a6e4f2aaca73c9e5a280e4c48856e9cc5fe1ba9a5c3f3cdd8a80d0b81f358b6c7b27088b7618f45db1e767b2e8d85d2d53d6ec9433c33a0c11877feec114d",
          "sha256": "1e111d5ec6d1db167c4fc9648dce57f553eaedd8ba914a2e9e8f06684e0d9361",
          "sha1": "25c5c68275eb337b0af5cbbaf91d186749f55d0f",
          "md5": "95f81f7411065e1c56a697f1de1c5739"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.18+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.6.1+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.7+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.2+1.21"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "5.14.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.12+1.21.1.jar",
          "url": "filament-1.3.12+1.21.1.jar",
          "size": 2846641,
          "sha512": "ab5a6e4f2aaca73c9e5a280e4c48856e9cc5fe1ba9a5c3f3cdd8a80d0b81f358b6c7b27088b7618f45db1e767b2e8d85d2d53d6ec9433c33a0c11877feec114d",
          "sha256": "1e111d5ec6d1db167c4fc9648dce57f553eaedd8ba914a2e9e8f06684e0d9361",
          "sha1": "25c5c68275eb337b0af5cbbaf91d186749f55d0f",
          "md5": "95f81f7411065e1c56a697f1de1c5739"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.12+1.21.1-sources.jar",
          "url": "filament-1.3.12+1.21.1-sources.jar",
          "size": 376408,
          "sha512": "eb2f8fb0d621de8d54d0ebc8e30e269e98a71b10e25da6a5557df99e4f3687a9f78aa12cddbc346c3ca3a8125befa6867c213f33778c374cb5e4cfa53e1dce10",
          "sha256": "3e6cf97bd8e5a69a9e1b39cd6f483359f03d428c94ba62c042221b4d8d71fb81",
          "sha1": "e5b7c0ad7f98a5a35fdd0afbcc0c49e53f9db49d",
          "md5": "2f00d7cbd9679465f8ff7a8d907fb3c0"
        }
      ]
    }
  ]
}
