{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.14.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.14.3+1.21.1.jar",
          "url": "filament-0.14.3+1.21.1.jar",
          "size": 1403181,
          "sha512": "49fb3036db7319314a8b07714e175bf6cb3de05fcb395a9a6414dcf0baa5d5bc8acb2613ae6f1b11389e89453d6caef6a04b077673d3b20640db7ebae0c91d90",
          "sha256": "67e71b3b3fff71a1cfabb7829ce0e2ab1143c130a640ecd61868cc811d5cca09",
          "sha1": "dfacd362efe2a57991fc61cb7e0287ce57b1a451",
          "md5": "fd80f5527e1124f8ec59c946f2569834"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.1+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.3+1.21.1.jar",
          "url": "filament-0.14.3+1.21.1.jar",
          "size": 1403181,
          "sha512": "49fb3036db7319314a8b07714e175bf6cb3de05fcb395a9a6414dcf0baa5d5bc8acb2613ae6f1b11389e89453d6caef6a04b077673d3b20640db7ebae0c91d90",
          "sha256": "67e71b3b3fff71a1cfabb7829ce0e2ab1143c130a640ecd61868cc811d5cca09",
          "sha1": "dfacd362efe2a57991fc61cb7e0287ce57b1a451",
          "md5": "fd80f5527e1124f8ec59c946f2569834"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.3+1.21.1-all.jar",
          "url": "filament-0.14.3+1.21.1-all.jar",
          "size": 844882,
          "sha512": "423bd3eb4af47e9302bb6b15cdf91cfea81ebacb62177bab4c437f985d9f6ecf5ce73fa684683f0bbde6b588c63017d42e20328e7d2bbce45bb9adde2e8c4659",
          "sha256": "785056417b939a83005565827eeb2ed2596c96b2ddef7afae7fd84f4159fdc5b",
          "sha1": "5177b0a8dc83a4420a2ce530a1cc7caeebdc534f",
          "md5": "515c56195f81c309bd92ed99195f0f36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.14.3+1.21.1-sources.jar",
          "url": "filament-0.14.3+1.21.1-sources.jar",
          "size": 207948,
          "sha512": "763e77b1a787f17ef44f9744b5db297f646cfed553f89753e7e6956523da9ff79b8f4baf4ef7da029efbf58baa2427f328c7171374389862717cea58b9cb241f",
          "sha256": "2c0d5cd39db775fa580aeb260e39bb834032ffa43390949db6006ad8ba26bd67",
          "sha1": "c6ae05a01dad46f6fa4de267aceb78f7b5f764c9",
          "md5": "cf6bfc4e68bc2fc0cab9a0cc7317a546"
        }
      ]
    }
  ]
}
