{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library-neo",
    "version": "2.0.5+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.5+26.1.jar",
          "url": "blockbench-import-library-neo-2.0.5+26.1.jar",
          "size": 352732,
          "sha512": "7a0975d9acdf6fe290cc4044a3db8d11d07b56020ce6d0b48cf7a0a670be6d9538d3bc4079629c1203fe70606b566f801bbe6a7851e194a32420be6084db6e9d",
          "sha256": "5b15632ebf08a55b03b3f7abcde52ee4fc13e0b7061e5fb4da5e31d4cf2f4183",
          "sha1": "81fd990e5a27974399d15452209395bad19de8a1",
          "md5": "cfabb59f423d41b1925f3a52648e4834"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "eu.pb4",
          "module": "polymer-core-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost-neo",
          "version": {
            "requires": "0.16.5+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.5+26.1.jar",
          "url": "blockbench-import-library-neo-2.0.5+26.1.jar",
          "size": 352732,
          "sha512": "7a0975d9acdf6fe290cc4044a3db8d11d07b56020ce6d0b48cf7a0a670be6d9538d3bc4079629c1203fe70606b566f801bbe6a7851e194a32420be6084db6e9d",
          "sha256": "5b15632ebf08a55b03b3f7abcde52ee4fc13e0b7061e5fb4da5e31d4cf2f4183",
          "sha1": "81fd990e5a27974399d15452209395bad19de8a1",
          "md5": "cfabb59f423d41b1925f3a52648e4834"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.5+26.1-sources.jar",
          "url": "blockbench-import-library-neo-2.0.5+26.1-sources.jar",
          "size": 121012,
          "sha512": "2c40cc45da3c988e3dc9cf09d6836080f9f91598a6c821446684f9089b7bad1d1948d837da4fbb954448fb0e9c4d264002d94bce9d3743f93fab0bfd02bf07a9",
          "sha256": "652e8e50602edbeb32f43473fdd0d0e51b3d3593b30f11b5011fa06c722585ef",
          "sha1": "7bce05b772501134ebd97c50a34a3f2fa40417d0",
          "md5": "d9f8b8fd49122a9a3ffed492f9c30d2d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-neo-2.0.5+26.1.jar",
          "url": "blockbench-import-library-neo-2.0.5+26.1.jar",
          "size": 352732,
          "sha512": "7a0975d9acdf6fe290cc4044a3db8d11d07b56020ce6d0b48cf7a0a670be6d9538d3bc4079629c1203fe70606b566f801bbe6a7851e194a32420be6084db6e9d",
          "sha256": "5b15632ebf08a55b03b3f7abcde52ee4fc13e0b7061e5fb4da5e31d4cf2f4183",
          "sha1": "81fd990e5a27974399d15452209395bad19de8a1",
          "md5": "cfabb59f423d41b1925f3a52648e4834"
        }
      ]
    }
  ]
}
