{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.14.5+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.14.5+1.21.1.jar",
          "url": "filament-0.14.5+1.21.1.jar",
          "size": 1404354,
          "sha512": "38d997dda5f0b811df4ab8502fb1c71c7ca22afedcc58c4db98b36da087b8d4b0d5b2a30e87906e50b3dfd1da075ad73c6cca7ea83c17cd3951936a0173eecc4",
          "sha256": "76a809d510417e4c4331682705453118d81fce93bfea7928be0a5214101daa0c",
          "sha1": "6a31b1651a000ca10c59f8d8437ff78a94afb451",
          "md5": "13579c534696010af922837870185e94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.1+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.5+1.21.1.jar",
          "url": "filament-0.14.5+1.21.1.jar",
          "size": 1404354,
          "sha512": "38d997dda5f0b811df4ab8502fb1c71c7ca22afedcc58c4db98b36da087b8d4b0d5b2a30e87906e50b3dfd1da075ad73c6cca7ea83c17cd3951936a0173eecc4",
          "sha256": "76a809d510417e4c4331682705453118d81fce93bfea7928be0a5214101daa0c",
          "sha1": "6a31b1651a000ca10c59f8d8437ff78a94afb451",
          "md5": "13579c534696010af922837870185e94"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.5+1.21.1-all.jar",
          "url": "filament-0.14.5+1.21.1-all.jar",
          "size": 846053,
          "sha512": "3e006fc98e57ca51ef6304c55604ec30c1eeb4188b985318b0cc1581560811a8b21d839c86695a3045b0ea85625c87711e9f5a7d05729d0c660eb48f6c7a09ed",
          "sha256": "66e8d5b9b7f548e145ddebe8e567e659e25506f5c85cada6d0f6026c9371896c",
          "sha1": "48f6c537f664803ae4c27a1f89143a5430647612",
          "md5": "5244da1bce8eeca9f7e9e589126ba112"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.14.5+1.21.1-sources.jar",
          "url": "filament-0.14.5+1.21.1-sources.jar",
          "size": 208485,
          "sha512": "c88cec18967d9a58464c8462be8b099a2c75ce40a06d9c83f4bbd79d857172eec9d61983e138255c2e7e45c722d07acb7adec0ca7282d3a0ed1f601ecf187be9",
          "sha256": "87d713fae5cd4b511bc519cd8c9a300f7e30297b467be5ac0a35f513b04d844c",
          "sha1": "9f11065caf2bf075a159f999afbebdd0e598032d",
          "md5": "536a5ce38e71ad24357366cb26636e78"
        }
      ]
    }
  ]
}
