{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.5.1+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.5.1+1.21.jar",
          "url": "filament-0.5.1+1.21.jar",
          "size": 584824,
          "sha512": "6d9db4f33cba392d6a02563dfc50b6f3229bdc1bfd0acb0f060caf3806bffc35e103057a66e597804612beba202a160f5c2a043dfd82803ec5f8c54e90628cfb",
          "sha256": "6a4ebb4e0a0714d3bdb83ed634fac7060bc769813742a7281d15e4c0cc4c1958",
          "sha1": "2fed29529309a312a00e2253a5f68bf4aa3d010e",
          "md5": "6fe5544c4f0c96497ddbb3839d77ebcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.2+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.2+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.2+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.2+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.2+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.2+1.21"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.9+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.5.1+1.21.jar",
          "url": "filament-0.5.1+1.21.jar",
          "size": 584824,
          "sha512": "6d9db4f33cba392d6a02563dfc50b6f3229bdc1bfd0acb0f060caf3806bffc35e103057a66e597804612beba202a160f5c2a043dfd82803ec5f8c54e90628cfb",
          "sha256": "6a4ebb4e0a0714d3bdb83ed634fac7060bc769813742a7281d15e4c0cc4c1958",
          "sha1": "2fed29529309a312a00e2253a5f68bf4aa3d010e",
          "md5": "6fe5544c4f0c96497ddbb3839d77ebcc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.5.1+1.21-sources.jar",
          "url": "filament-0.5.1+1.21-sources.jar",
          "size": 102080,
          "sha512": "2bc35c58fecdb9e825ec372bd465bd4377271b65ca8103fe975136d07a898b417f97b04a29cffb4ae47e1eecbb50a3082644c0bd954cce82f90de6c326bbaf0a",
          "sha256": "ef869f5ba0a1cc8d571de67555d4124094c7055d409d90b742ded32571aa4494",
          "sha1": "5c8c61a37d875545ce2047beb67649259831bee9",
          "md5": "0225cfeb2b28b69880be840b1a42fc6e"
        }
      ]
    }
  ]
}
