{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.12.5+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.12.5+1.21.1.jar",
          "url": "filament-0.12.5+1.21.1.jar",
          "size": 1358637,
          "sha512": "1e164788153d853615f29eacbb4e668609c5e929072d2f282236fe406f82d2573a24ed4133487729b9c9990b09d28988e1d0d0bd81e633400affd3f808724130",
          "sha256": "19f1dd087581e33249ac0f5b04bea7f65aafee824fcd8b19f9e36e106a1e4b4b",
          "sha1": "b8e5202ddd3375d9921ac9b8c32507786a96ee36",
          "md5": "e885947496a78e97a926eeed179edc71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.20+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.5+1.21.1.jar",
          "url": "filament-0.12.5+1.21.1.jar",
          "size": 1358637,
          "sha512": "1e164788153d853615f29eacbb4e668609c5e929072d2f282236fe406f82d2573a24ed4133487729b9c9990b09d28988e1d0d0bd81e633400affd3f808724130",
          "sha256": "19f1dd087581e33249ac0f5b04bea7f65aafee824fcd8b19f9e36e106a1e4b4b",
          "sha1": "b8e5202ddd3375d9921ac9b8c32507786a96ee36",
          "md5": "e885947496a78e97a926eeed179edc71"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.12.5+1.21.1-all.jar",
          "url": "filament-0.12.5+1.21.1-all.jar",
          "size": 799888,
          "sha512": "a9133ca03bbf9a8196e50eb7e6da6c65e6ff957cf9a0223e288d6cef2d4fb3c8f68c4c31d7d0e8f2d9878981c30af1d53972d94633c076a21190253ccd506491",
          "sha256": "1a0ae2294559fe94ab422f2539d4ffeba4897081325675b04bbafae48e2d2fe7",
          "sha1": "6bea0df5cee78f326ef688e8765fc4393a6282e8",
          "md5": "1793a4ce66328de6851b03a7b9f3e029"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.12.5+1.21.1-sources.jar",
          "url": "filament-0.12.5+1.21.1-sources.jar",
          "size": 189603,
          "sha512": "9f323ae291c3d724281d3af2db6fb619a7693e0bc5744729db03fdf5703f5e81e08f41914713e91b259d3230d2f7cf5599279d7ba01df7837a0ef7fb3a245ee0",
          "sha256": "be90270f8014c05a46800c139e1f82bd975de42111114eee1ce30c7e630e8117",
          "sha1": "2f562bca446d6a038b42444d10deb9673db8c551",
          "md5": "3fae113152adb2a05d8fa6bd2ea8ee96"
        }
      ]
    }
  ]
}
