{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "1.3.16+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-1.3.16+1.21.10.jar",
          "url": "filament-1.3.16+1.21.10.jar",
          "size": 3061513,
          "sha512": "233f74a38963740dd25a60896c577081ae5ee3eb0b6f6b94096d9b0f2e45cabbf512570fd65a2f4143fadf34ab96a8a25aa17f2ed6f85ffcbf2b8ddf81f29b96",
          "sha256": "986fceb133a9c144aeb392a9e4607230ae5143d9bba28607c74fcc8d46c1f04a",
          "sha1": "65a826a55a466b757f3cfc56611a55d14f705e51",
          "md5": "1ced0f66aaa0b5f956db26a677ae6a7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-sound-patcher",
          "version": {
            "requires": "0.14.3+1.21.10"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "1.10.2+1.21.8"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.7.2+1.21.9"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.8.1+1.21.10"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "eu.pb4",
          "module": "common-protection-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-1.3.16+1.21.10.jar",
          "url": "filament-1.3.16+1.21.10.jar",
          "size": 3061513,
          "sha512": "233f74a38963740dd25a60896c577081ae5ee3eb0b6f6b94096d9b0f2e45cabbf512570fd65a2f4143fadf34ab96a8a25aa17f2ed6f85ffcbf2b8ddf81f29b96",
          "sha256": "986fceb133a9c144aeb392a9e4607230ae5143d9bba28607c74fcc8d46c1f04a",
          "sha1": "65a826a55a466b757f3cfc56611a55d14f705e51",
          "md5": "1ced0f66aaa0b5f956db26a677ae6a7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-1.3.16+1.21.10-sources.jar",
          "url": "filament-1.3.16+1.21.10-sources.jar",
          "size": 373722,
          "sha512": "bbbcd23a22d2e379ef422ba0afae4ca40e12d51d5ce0eb428ddf0467a31d90088fe1d35ebd4ee172e3d9cdefe5db14c972c51e2cdffd53429e1427ec2383033c",
          "sha256": "7fd060323413c35a5d0f0348deb611fb274623b19a4ad204343977d2db6448e2",
          "sha1": "9a7631669361fadd6192fb3f600d94eefc10368c",
          "md5": "4a86437f74d24acebad93168f9a757d5"
        }
      ]
    }
  ]
}
