{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "1.8.4+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-1.8.4+1.21.11.jar",
          "url": "blockbench-import-library-1.8.4+1.21.11.jar",
          "size": 356006,
          "sha512": "0fcde2feb9191d1360460936775b58d016ac6207d7d6622aff7a9948b31b0a8cc67d54542b152fc7ad722ff51fe819aa3632d34ba1da3898d62f035d291bca26",
          "sha256": "8f405c8531b0c9e9cf45d282d873ef62851cae5dc01db90cbd9334fa8ca3abf5",
          "sha1": "a03fba66244b2f0e6f057cd8e19eadbd11cec33e",
          "md5": "5d9f4068f32d2c4284233abcb85293cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-1.8.4+1.21.11.jar",
          "url": "blockbench-import-library-1.8.4+1.21.11.jar",
          "size": 356006,
          "sha512": "0fcde2feb9191d1360460936775b58d016ac6207d7d6622aff7a9948b31b0a8cc67d54542b152fc7ad722ff51fe819aa3632d34ba1da3898d62f035d291bca26",
          "sha256": "8f405c8531b0c9e9cf45d282d873ef62851cae5dc01db90cbd9334fa8ca3abf5",
          "sha1": "a03fba66244b2f0e6f057cd8e19eadbd11cec33e",
          "md5": "5d9f4068f32d2c4284233abcb85293cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-1.8.4+1.21.11-sources.jar",
          "url": "blockbench-import-library-1.8.4+1.21.11-sources.jar",
          "size": 122840,
          "sha512": "17c6df4b2b1c32e697b0ea938aa8242d78e56b004b83859c569db7e17ffc081a91e82c9246b3096332f71e315b71143d3de7da87bf68ad47729e5ad2465023aa",
          "sha256": "24d9ddcc3364a35f9ce5f2ee740c4bbaf4bf380c8dcdf433c8ccb2c8113b10b9",
          "sha1": "5cd5cd9e110f2a7c69ad26f92e3175c233fa7c7c",
          "md5": "0d4dfd35f5c8172749349c2e4d94f524"
        }
      ]
    }
  ]
}
