{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "blockbench-import-library",
    "version": "1.9.0-beta1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blockbench-import-library-1.9.0-beta1+1.21.11.jar",
          "url": "blockbench-import-library-1.9.0-beta1+1.21.11.jar",
          "size": 357634,
          "sha512": "71a7137d98ffbfa713a3402c9bb0e169430ad2163d875f383a862e500b57091702fc3949f7f57caea50eb1e8fbe7eb88594d6993352d7dbe0839e26d98eedc52",
          "sha256": "e6d93639149a7bbe96b3c6a7be5e62dd430a98376e3629e84f3c5378ac6a310d",
          "sha1": "621d36bcd2cafa5c43af9dc8fdd55d64ff09d396",
          "md5": "c6af5faae2c23fd5111aace2e43a97d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack-extras",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.15.0-beta.4+1.21.11-rc2"
          }
        }
      ],
      "files": [
        {
          "name": "blockbench-import-library-1.9.0-beta1+1.21.11.jar",
          "url": "blockbench-import-library-1.9.0-beta1+1.21.11.jar",
          "size": 357634,
          "sha512": "71a7137d98ffbfa713a3402c9bb0e169430ad2163d875f383a862e500b57091702fc3949f7f57caea50eb1e8fbe7eb88594d6993352d7dbe0839e26d98eedc52",
          "sha256": "e6d93639149a7bbe96b3c6a7be5e62dd430a98376e3629e84f3c5378ac6a310d",
          "sha1": "621d36bcd2cafa5c43af9dc8fdd55d64ff09d396",
          "md5": "c6af5faae2c23fd5111aace2e43a97d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blockbench-import-library-1.9.0-beta1+1.21.11-sources.jar",
          "url": "blockbench-import-library-1.9.0-beta1+1.21.11-sources.jar",
          "size": 123087,
          "sha512": "4eec354d0937deb39be4f894fb2ffbc2bf4a161353ecf907b66b5300649da30b1f12921c5aa9a5c51c173386be3473c887ea93fcfb76a988a83eda7a8ace71d5",
          "sha256": "a0178f0a9cb46aceb6bcc3e339b7e5bf696be57af127d7ab2cf31f401772f27c",
          "sha1": "2c0680943ab57041cb1ed9f1e9b62de6229053bd",
          "md5": "1ca15ab15805a27de23c7f9618026856"
        }
      ]
    }
  ]
}
