{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.14.10+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.14.10+1.21.1.jar",
          "url": "filament-0.14.10+1.21.1.jar",
          "size": 1429986,
          "sha512": "866eb50a753de07863ad97f330a509278a95f5c5b994dd180b49c027a2c1fc1532a80b405f615d2a86b796ded0e6ee51cec992c0d5c88e7b00df9c4756a7937a",
          "sha256": "5bb69f191b354d0fcd35fff0e250fec4d307dee2beb8c5b624a5e4de1d9e42fc",
          "sha1": "7400842915e69803311271d5449769e855be4e26",
          "md5": "890b23cbe1c22e7c484bc54dbaab0c1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.17+1.21.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.2.1+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.10+1.21.1.jar",
          "url": "filament-0.14.10+1.21.1.jar",
          "size": 1429986,
          "sha512": "866eb50a753de07863ad97f330a509278a95f5c5b994dd180b49c027a2c1fc1532a80b405f615d2a86b796ded0e6ee51cec992c0d5c88e7b00df9c4756a7937a",
          "sha256": "5bb69f191b354d0fcd35fff0e250fec4d307dee2beb8c5b624a5e4de1d9e42fc",
          "sha1": "7400842915e69803311271d5449769e855be4e26",
          "md5": "890b23cbe1c22e7c484bc54dbaab0c1d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.14.10+1.21.1-all.jar",
          "url": "filament-0.14.10+1.21.1-all.jar",
          "size": 871678,
          "sha512": "835c1d5800f3fa8435fe370f3179860ed9efb3022d1045f8a4219368138f06d15f6be5ee2db8c6113599fd8f317366fa8124b10394b30ccaa5710bd9b719d997",
          "sha256": "0df8c2d969cb28b68cbd0eb5982aae0f939c9e3a100fdb0e2d98eb1282f22865",
          "sha1": "8fea82843aeff545bd8562f0b9bef016f42e6e70",
          "md5": "993d112a716fdc0279fec8da47305f11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.14.10+1.21.1-sources.jar",
          "url": "filament-0.14.10+1.21.1-sources.jar",
          "size": 221540,
          "sha512": "a0d63788422d1bde31971734532623fd5b54163fce988801271670e47329ae4567b24192529005b61582813526a68f073b72d7cc405fce73d22b654b30f1f535",
          "sha256": "7d588669d430cd3e5b04d5bb4f0e1338af9c5fc2cedba4130dd3445d1098a293",
          "sha1": "66f419f485a3d28dbaf3270463839c79ed906e48",
          "md5": "08b4263cf6dcca48eeca0309ccaeb698"
        }
      ]
    }
  ]
}
