{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.8.6+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.8.6+1.21.jar",
          "url": "filament-0.8.6+1.21.jar",
          "size": 824529,
          "sha512": "3f1feb3e107ee86065405a2b1d0995880a2f50e6aaf0bc382ea1ae4ccb5b9f2438e14157894f05f81b6184a3cf175adf9262d2d575561a0c0df7e18a889eaa69",
          "sha256": "21e45f1207ccf78f322b4daffc56c4991abba96792a5c1498cbe6540878f84c8",
          "sha1": "7030c17070cd6a812e2c4968d35e154839d1e873",
          "md5": "bbb89b12ccddb8ad5390e3825caa2d9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.8.6+1.21.jar",
          "url": "filament-0.8.6+1.21.jar",
          "size": 824529,
          "sha512": "3f1feb3e107ee86065405a2b1d0995880a2f50e6aaf0bc382ea1ae4ccb5b9f2438e14157894f05f81b6184a3cf175adf9262d2d575561a0c0df7e18a889eaa69",
          "sha256": "21e45f1207ccf78f322b4daffc56c4991abba96792a5c1498cbe6540878f84c8",
          "sha1": "7030c17070cd6a812e2c4968d35e154839d1e873",
          "md5": "bbb89b12ccddb8ad5390e3825caa2d9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.8.6+1.21-sources.jar",
          "url": "filament-0.8.6+1.21-sources.jar",
          "size": 137526,
          "sha512": "1e9932864530f60d3c49cbe17532a5d67f1c707d53b2c0ec1c50526f03ce23473ab5f8609284c5f7587cbf3942ddf86ef4366fbc356795dbb652d2bf0c658e90",
          "sha256": "471b045c3f801f686b418e17780df1ed509a183183bb25ca6ba43c61cd91b6ba",
          "sha1": "1297e778180e5ee9eaf43ad455222cb7e6ee1f8b",
          "md5": "457e7d2b60b90e436283cf208cd56266"
        }
      ]
    }
  ]
}
