{
  "formatVersion": "1.1",
  "component": {
    "group": "de.tomalbrc",
    "module": "filament",
    "version": "0.8.5+1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filament-0.8.5+1.21.jar",
          "url": "filament-0.8.5+1.21.jar",
          "size": 822065,
          "sha512": "fca99210f5eef0132b7fb05416e8491247409d595ca33001e5c22f7513c8ad5338420ad66a95f48980e8a90bbf897c2e6735d1aa3df0f2db4800b129e419ced2",
          "sha256": "2bd80d82671eb84190babd9b233c3160920ec9855055e5353082a318fa93eb82",
          "sha1": "991bbdecf35a585f7a307ebe8c2a2c9fd6a23e53",
          "md5": "11fa558dafcb2f7f3c73946f81ad369b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.4+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-core",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-blocks",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-virtual-entity",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-networking",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-autohost",
          "version": {
            "requires": "0.9.14+1.21.1"
          }
        },
        {
          "group": "de.tomalbrc",
          "module": "blockbench-import-library",
          "version": {
            "requires": "1.1.12+1.21"
          }
        },
        {
          "group": "eu.pb4",
          "module": "placeholder-api",
          "version": {
            "requires": "2.4.0+1.21"
          }
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "filament-0.8.5+1.21.jar",
          "url": "filament-0.8.5+1.21.jar",
          "size": 822065,
          "sha512": "fca99210f5eef0132b7fb05416e8491247409d595ca33001e5c22f7513c8ad5338420ad66a95f48980e8a90bbf897c2e6735d1aa3df0f2db4800b129e419ced2",
          "sha256": "2bd80d82671eb84190babd9b233c3160920ec9855055e5353082a318fa93eb82",
          "sha1": "991bbdecf35a585f7a307ebe8c2a2c9fd6a23e53",
          "md5": "11fa558dafcb2f7f3c73946f81ad369b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filament-0.8.5+1.21-sources.jar",
          "url": "filament-0.8.5+1.21-sources.jar",
          "size": 136498,
          "sha512": "8e173f33552e7a71fe61955cdaf32e4efb55155d5c5a4f4de7763098799b66f7ddc507f4c1d2f6506a091043ca901e7a8ed1fe635d768d6af1aa810273fed91e",
          "sha256": "e26b49a351de159d8bb0c835187faf99f189153f4f3cafd1314c0fb56e382d87",
          "sha1": "9458e7a5b568d4cd9f604f785ddda3e98bc33d17",
          "md5": "b716e72d33d86cb2cdd71ecf61e4cde7"
        }
      ]
    }
  ]
}
